### ISSUE TITLE
[Dev] 6.0.3 errors

### ISSUE THREAD

**Issue by DDuarte** [TrinityCore/WowPacketParser#141]
Wrongly parsed packets (with errors):

- SMSG_0x0089
- SMSG_0x0503
- SMSG_0x0713
- SMSG_0x0732
- SMSG_0x0733
- SMSG_0x0758
- SMSG_0x0791
- SMSG_0x0794
- SMSG_0x0807
- SMSG_0x0D3D
- SMSG_0x0D52
- SMSG_0x0F11
- SMSG_0x1142
- SMSG_0x11C1
- SMSG_0x15C4
- SMSG_0x17C9
- SMSG_0x19D2
- SMSG_0x1DBD
- SMSG_BATTLEFIELD_MGR_DROP_TIMER_STARTED
- SMSG_CALENDAR_EVENT_INVITE_STATUS
- SMSG_TITLE_LOST
- CMSG_0x010F
- CMSG_0x0301
- CMSG_0x0632
- CMSG_0x0734
- CMSG_0x0753
- CMSG_0x0932
- CMSG_0x11D9
- CMSG_0x14DB
- CMSG_0x160B
- CMSG_BATTLE_PET_UPDATE_NOTIFY
- CMSG_CALENDAR_EVENT_RSVP
- CMSG_CANCEL_MOD_SPEED_NO_CONTROL_AURAS
- CMSG_CHANGE_SUB_GROUP
- CMSG_COMPLAIN
- CMSG_DECLINE_PETITION
- CMSG_DELETE_EQUIPMENT_SET
- CMSG_EJECT_PASSENGER
- CMSG_GUILD_BANK_SET_TAB_TEXT
- CMSG_GUILD_BANK_SWAP_ITEMS
- CMSG_GUILD_UPDATE_MOTD_TEXT
- CMSG_ITEM_PURCHASE_REFUND
- CMSG_JOIN_ARENA_SKIRMISH
- CMSG_LFG_LIST_CANCEL_APPLICATION
- CMSG_LFG_LIST_DECLINE_APPLICANT
- CMSG_LFG_LIST_INVITE_APPLICANT
- CMSG_LF_GUILD_REMOVE_RECRUIT
- CMSG_MOVE_SET_IGNORE_MOVEMENT_FORCES_ACK
- CMSG_OFFER_PETITION
- CMSG_PETITION_BUY
- CMSG_PETITION_RENAME_GUILD
- CMSG_PETITION_SHOW_SIGNATURES
- CMSG_QUERY_INSPECT_ACHIEVEMENTS
- CMSG_REAGENT_BANK_BUY_TAB
- CMSG_REQUEST_STABLED_PETS
- CMSG_RIDE_VEHICLE_INTERACT
- CMSG_SET_ASSISTANT_LEADER
- CMSG_SET_CONTACT_NOTES
- CMSG_SET_EVERYONE_IS_ASSISTANT
- CMSG_SOCKET_GEMS
- CMSG_SUMMON_RESPONSE
- CMSG_SUPPORT_TICKET_SUBMIT_COMPLAINT
- CMSG_SWAP_SUB_GROUPS
- CMSG_TURN_IN_PETITION
- CMSG_UPGRADE_ITEM

Rev 09c76d4f719317a579f14bb6dc1d2796c42fc57a

**Comment by Aokromes** [comment]
test

**Comment by Aokromes** [comment]
test

**Comment by msoky** [comment]
wtf? :D

**Comment by Aokromes** [comment]
Testing to fix commits bot :P

**Comment by DDuarte** [comment]
First post updated

**Comment by DDuarte** [comment]
First post updated

**Comment by DDuarte** [comment]
First post updated

**Comment by Carbenium** [comment]
Not really up to date anymore. closing
