### ISSUE TITLE
[Dev] 6.0.3 missing

### ISSUE THREAD

**Issue by DDuarte** [TrinityCore/WowPacketParser#159]
- 1289 (0x0509)
- 1294 (0x050E)
- 1335 (0x0537)
- 1346 (0x0542)
- 137 (0x0089)
- 1381 (0x0565)
- 1571 (0x0623)
- 1612 (0x064C)
- 1755 (0x06DB)
- 1821 (0x071D)
- 1844 (0x0734)
- 1950 (0x079E)
- 1962 (0x07AA)
- 2090 (0x082A)
- 2294 (0x08F6)
- 2325 (0x0915)
- 2334 (0x091E)
- 2341 (0x0925)
- 2354 (0x0932)
- 2358 (0x0936)
- 2409 (0x0969)
- 2433 (0x0981)
- 2441 (0x0989)
- 2465 (0x09A1)
- 2497 (0x09C1)
- 2501 (0x09C5)
- 2510 (0x09CE)
- 2526 (0x09DE)
- 2599 (0x0A27)
- 260 (0x0104)
- 278 (0x0116)
- 279 (0x0117)
- 2790 (0x0AE6)
- 2839 (0x0B17)
- 2853 (0x0B25)
- 2856 (0x0B28)
- 2873 (0x0B39)
- 2906 (0x0B5A)
- 2998 (0x0BB6)
- 3018 (0x0BCA)
- 313 (0x0139)
- 322 (0x0142)
- 3686 (0x0E66)
- 3850 (0x0F0A)
- 39 (0x0027)
- 418 (0x01A2)
- 4353 (0x1101)
- 4386 (0x1122)
- 4418 (0x1142)
- 4425 (0x1149)
- 449 (0x01C1)
- 4490 (0x118A)
- 4652 (0x122C)
- 4746 (0x128A)
- 485 (0x01E5)
- 4899 (0x1323)
- 4938 (0x134A)
- 5017 (0x1399)
- 5050 (0x13BA)
- 5076 (0x13D4)
- 516 (0x0204)
- 5176 (0x1438)
- 522 (0x020A)
- 5257 (0x1489)
- 5282 (0x14A2)
- 5641 (0x1609)
- 5696 (0x1640)
- 5742 (0x166E)
- 5858 (0x16E2)
- 6179 (0x1823)
- 6482 (0x1952)
- 6508 (0x196C)
- 651 (0x028B)
- 6515 (0x1973)
- 653 (0x028D)
- 6530 (0x1982)
- 6545 (0x1991)
- 6587 (0x19BB)
- 6627 (0x19E3)
- 6970 (0x1B3A)
- 7027 (0x1B73)
- 7042 (0x1B82)
- 7065 (0x1B99)
- 707 (0x02C3)
- 7075 (0x1BA3)
- 7215 (0x1C2F)
- 7306 (0x1C8A)
- 7388 (0x1CDC)
- 757 (0x02F5)
- 769 (0x0301)
- 790 (0x0316)
- 797 (0x031D)
- 806 (0x0326)
- 822 (0x0336)
- 830 (0x033E)
- 923 (0x039B)
- 966 (0x03C6)
- CMSG_CHALLENGE_MODE_REQUEST_MAP_STATS (0x0E78)
- CMSG_CONFIRM_RESPEC_WIPE (0x14B4)
- CMSG_DUEL_RESPONSE (0x1BD2)
- CMSG_GUILD_QUERY_NEWS (0x0676)
- CMSG_QUEST_PUSH_RESULT (0x03D2)
- CMSG_SET_PRIMARY_TALENT_TREE (0x0AC5)
- CMSG_SET_SORT_BAGS_RIGHT_TO_LEFT (0x089D)
- 1001 (0x03E9)
- 115 (0x0073)
- 13 (0x000D)
- 1305 (0x0519)
- 1306 (0x051A)
- 1327 (0x052F)
- 1341 (0x053D)
- 1422 (0x058E)
- 1454 (0x05AE)
- 1456 (0x05B0)
- 1625 (0x0659)
- 1739 (0x06CB)
- 1822 (0x071E)
- 1846 (0x0736)
- 1876 (0x0754)
- 1934 (0x078E)
- 1937 (0x0791)
- 1941 (0x0795)
- 1943 (0x0797)
- 1950 (0x079E)
- 2063 (0x080F)
- 2087 (0x0827)
- 210 (0x00D2)
- 2187 (0x088B)
- 2317 (0x090D)
- 2318 (0x090E)
- 2319 (0x090F)
- 2325 (0x0915)
- 2327 (0x0917)
- 2350 (0x092E)
- 2442 (0x098A)
- 2467 (0x09A3)
- 2475 (0x09AB)
- 2501 (0x09C5)
- 2525 (0x09DD)
- 2529 (0x09E1)
- 2532 (0x09E4)
- 2574 (0x0A0E)
- 259 (0x0103)
- 2606 (0x0A2E)
- 261 (0x0105)
- 262 (0x0106)
- 2694 (0x0A86)
- 272 (0x0110)
- 2749 (0x0ABD)
- 2842 (0x0B1A)
- 2875 (0x0B3B)
- 2882 (0x0B42)
- 2884 (0x0B44)
- 2955 (0x0B8B)
- 2969 (0x0B99)
- 3027 (0x0BD3)
- 304 (0x0130)
- 3065 (0x0BF9)
- 311 (0x0137)
- 3275 (0x0CCB)
- 3358 (0x0D1E)
- 3359 (0x0D1F)
- 3360 (0x0D20)
- 3374 (0x0D2E)
- 3375 (0x0D2F)
- 3385 (0x0D39)
- 3389 (0x0D3D)
- 3390 (0x0D3E)
- 3472 (0x0D90)
- 3520 (0x0DC0)
- 3857 (0x0F11)
- 388 (0x0184)
- 394 (0x018A)
- 3986 (0x0F92)
- 403 (0x0193)
- 4107 (0x100B)
- 4120 (0x1018)
- 4129 (0x1021)
- 4165 (0x1045)
- 4168 (0x1048)
- 4200 (0x1068)
- 4371 (0x1113)
- 443 (0x01BB)
- 444 (0x01BC)
- 4452 (0x1164)
- 4482 (0x1182)
- 4491 (0x118B)
- 4514 (0x11A2)
- 4529 (0x11B1)
- 4614 (0x1206)
- 4695 (0x1257)
- 477 (0x01DD)
- 4883 (0x1313)
- 489 (0x01E9)
- 492 (0x01EC)
- 5009 (0x1391)
- 5028 (0x13A4)
- 5033 (0x13A9)
- 5060 (0x13C4)
- 5321 (0x14C9)
- 5396 (0x1514)
- 5421 (0x152D)
- 5439 (0x153F)
- 5517 (0x158D)
- 5535 (0x159F)
- 5549 (0x15AD)
- 5554 (0x15B2)
- 5587 (0x15D3)
- 5897 (0x1709)
- 6039 (0x1797)
- 6062 (0x17AE)
- 6077 (0x17BD)
- 6198 (0x1836)
- 6282 (0x188A)
- 6315 (0x18AB)
- 6401 (0x1901)
- 6420 (0x1914)
- 6530 (0x1982)
- 6540 (0x198C)
- 6634 (0x19EA)
- 6915 (0x1B03)
- 693 (0x02B5)
- 6980 (0x1B44)
- 6986 (0x1B4A)
- 6993 (0x1B51)
- 7004 (0x1B5C)
- 701 (0x02BD)
- 7044 (0x1B84)
- 7073 (0x1BA1)
- 7076 (0x1BA4)
- 7122 (0x1BD2)
- 7137 (0x1BE1)
- 7138 (0x1BE2)
- 741 (0x02E5)
- 7441 (0x1D11)
- 7443 (0x1D13)
- 756 (0x02F4)
- 773 (0x0305)
- 787 (0x0313)
- 7949 (0x1F0D)
- 797 (0x031D)
- 804 (0x0324)
- 818 (0x0332)
- 831 (0x033F)
- 833 (0x0341)
- 835 (0x0343)
- 918 (0x0396)
- 932 (0x03A4)
- 948 (0x03B4)
- SMSG_BATTLEFIELD_LIST (0x11A1)
- SMSG_BATTLEFIELD_STATUS_ACTIVE (0x1284)
- SMSG_BATTLEFIELD_STATUS_FAILED (0x0308)
- SMSG_BATTLEFIELD_STATUS_NEEDCONFIRMATION (0x1719)
- SMSG_BATTLEFIELD_STATUS_NONE (0x1E89)
- SMSG_BATTLEFIELD_STATUS_QUEUED (0x002D)
- SMSG_BATTLEGROUND_PLAYER_JOINED (0x13EA)
- SMSG_BATTLEGROUND_PLAYER_LEFT (0x1BD1)
- SMSG_BATTLEGROUND_PLAYER_POSITIONS (0x1BE9)
- SMSG_BATTLEGROUND_POINTS (0x122A)
- SMSG_BATTLE_PET_FINALIZE_LOCATION (0x0F09)
- SMSG_BATTLE_PET_FINAL_ROUND (0x05BA)
- SMSG_BATTLE_PET_FIRST_ROUND (0x1981)
- SMSG_BATTLE_PET_INITIAL_UPDATE (0x0D19)
- SMSG_BATTLE_PET_REPLACEMENTS_MADE (0x1B83)
- SMSG_BATTLE_PET_REQUEST_FAILED (0x1353)
- SMSG_BATTLE_PET_SLOT_UPDATES (0x1D8F)
- SMSG_BATTLE_PET_UPDATES (0x0354)
- SMSG_CHALLENGE_MODE_ALL_MAP_STATS (0x1CC9)
- SMSG_CHALLENGE_MODE_REQUEST_LEADERS_RESULT (0x07AA)
- SMSG_CHALLENGE_MODE_REWARDS (0x0904)
- SMSG_LFG_BOOT_PLAYER (0x07B3)
- SMSG_LF_GUILD_POST (0x1817)
- SMSG_LF_GUILD_RECRUITS (0x1008)
- SMSG_NEUTRAL_PLAYER_FACTION_SELECT_RESULT (0x0D0D)
- SMSG_PVP_OPTIONS_ENABLED (0x0320)
- SMSG_RANDOM_ROLL (0x1B04)
- SMSG_REQUEST_PVP_REWARDS_RESPONSE (0x1DAE)
- SMSG_RESPEC_WIPE_CONFIRM (0x1341)
- SMSG_ROLE_CHOSEN (0x07D3)

Rev 0272cd2

**Comment by Warpten** [comment]
CMSG_GROUP_SWAP_SUB_GROUP                               0x0106
CMSG_GROUP_REQUEST_JOIN_UPDATES                    0x071D
SMSG_PARTY_MEMBER_STATS_FULL                           0x0B8B

**Comment by soulfrost** [comment]
sort out cmsg and smsg pls -  cmsg and smsg can have same id...

**Comment by DDuarte** [comment]
I forgot about that detail, I'll re-do the list tonight.
