### ISSUE TITLE
Getting SubName in UnitTemplateNonWDB using GetName() doesn't seem right.

### ISSUE THREAD

**Issue by Epicurus4** [TrinityCore/WowPacketParser#161]
var name = StoreGetters.GetName(StoreNameType.Unit, (int) unit.Key.GetEntry(), false);
    var firstIndex = name.LastIndexOf('<');
    var lastIndex = name.LastIndexOf('>');
    if (firstIndex != -1 && lastIndex != -1)
    {
        var subname = name.Substring(firstIndex + 1, lastIndex - firstIndex - 1);

        if (_professionTrainers.Contains(subname))
            template.NpcFlag |= (uint) NPCFlags.ProfessionTrainer;
        else if (_classTrainers.Contains(subname))
            template.NpcFlag |= (uint) NPCFlags.ClassTrainer;
    }

It's the subname that's bracketed in <> and not the name. I don't think this will give you the result you're looking for.

**Comment by Epicurus4** [comment]
I'm too tired to update my fork at the moment, I can do it tomorrow and create a pull request - or you can take my fix here and apply it to the project:

    // has trainer flag but doesn't have prof nor class trainer flag
    if ((template.NpcFlag & (uint) NPCFlags.Trainer) != 0 &&
        ((template.NpcFlag & (uint) NPCFlags.ProfessionTrainer) == 0 ||
            (template.NpcFlag & (uint) NPCFlags.ClassTrainer) == 0))
    {
        UnitTemplate UnitData;
        if (Storage.UnitTemplates.TryGetValue((uint)unit.Key.GetEntry(), out UnitData))
        {
            if (_professionTrainers.Contains(UnitData.SubName))
                template.NpcFlag |= (uint) NPCFlags.ProfessionTrainer;
            else if (_classTrainers.Contains(UnitData.SubName))
                template.NpcFlag |= (uint) NPCFlags.ClassTrainer;
        }
    }

**Comment by Epicurus4** [comment]
https://github.com/TrinityCore/WowPacketParser/pull/162

**Comment by DDuarte** [comment]
729ec9eced13fe8c720295a719895b26ef803e42
