### ISSUE TITLE
[5.4.8] Rename opcode

### ISSUE THREAD

**Issue by ijustwantedtosayhi** [TrinityCore/WowPacketParser#165]
Hey guys. Could you please get the rename opcodes C/S - MSG and the structures for 18291/18414? Thanks!

**Comment by DDuarte** [comment]
How do we do that?

**Comment by ijustwantedtosayhi** [comment]
I have no idea. I guess you reverse engineer the executable with IDA. But I really don't know.

**Comment by DDuarte** [comment]
It's a very time consuming process and atm there's no benefit for TC (we only support 3.3.5 and 6.0.3) to do it.

We'll take pull requests fixing other versions but will not be able to fix those other versions ourselves.
