### ISSUE TITLE
Fields names from WPP not in sync with DB

### ISSUE THREAD

**Issue by danlapps** [TrinityCore/WowPacketParser#168]
Table item_template : has field ItemNameDescriptionID = DB has flagsCustom as second to last field.
Table Npc_text : all probability fields are :ProbX in DB
Table `quest_request_items` : Fields CompEmoteType and CompEmoteDelay are named EmoteOnComplete and EmoteOnCompleteDelay in DB
Table `broadcast_text` Field UnkMoP2 : DB has Unk2

**Comment by danlapps** [comment]
https://github.com/TrinityCore/WowPacketParser/pull/172/files

**Comment by Carbenium** [comment]
3ddbce572bddaf79c3d570cf406cc98d927acbad
