### ISSUE TITLE
SMSG_UNSET_CAN_FLY

### ISSUE THREAD

**Issue by et65** [TrinityCore/WowPacketParser#184]
SMSG_UNSET_CAN_FLY for 6.1 is not the right opcode.

**Comment by Vincent-Michael** [comment]
why?

**Comment by et65** [comment]
I think it's not the right the opcode. When i leave flying mount or I do .gm fly off i continue to fly :)

**Comment by Carbenium** [comment]
```
DEFINE_SERVER_OPCODE_HANDLER(SMSG_MOVE_UNSET_CAN_FLY,                      STATUS_UNHANDLED,    CONNECTION_TYPE_INSTANCE);
```

**Comment by et65** [comment]
Ohhh... My mistake. Sorry for inconvenience.

**Comment by Carbenium** [comment]
I'll check that out later.
