### ISSUE TITLE
Gameobject not found on sniffs

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/WowPacketParser#206]
I not sure if this is an issue.
The object 175124(Rookery Egg) type Trap is spawned on Blackrock Spire, it has the spell http://wotlk.openwow.com/spell=16474 on data3, this spell will summon another object: 175622 which also a trap and have the spell 15745 on data3 which summon the npc:10161

The problem is the object 175622  and the spell 15745 are not shown on sniffs (Even the template can not be found). On the 6.x DB the template is there, but I'm not sure if it's correct as the trap remain spawned after it cast the spell. Also need to know what happen when this gob spawn to finish the script.
##

**Comment by DDuarte** [comment]
Few years late, but this is normal behaviour of Blizz servers. Traps usually are not sent to the client. There's nothing that we can do on the parsing side.
