### ISSUE TITLE
[SQL-Output] `creature_text` - Unneeded '' for `BroadcastTextID`

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/WowPacketParser#208]
If the `creature_text` output is created you always get '' around the `BroadcastTextID`.

Example:

``` sql
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextID`, `comment`) VALUES
(14872, x, x, 'Help! I''m being chased by a swarm of bees!', 12, 1, 100, 0, 0, 0, '10259', 'Trok to 0'),
```

but it should be:

``` sql
(14872, x, x, 'Help! I''m being chased by a swarm of bees!', 12, 1, 100, 0, 0, 0, 10259, 'Trok to 0'),
```

instead. The '' is not needed for the broadcasttextid :)
##

**Comment by DDuarte** [comment]
Silly blub-guy, why the heck is `BroadcastTextID` a string?

**Comment by blasterdude9** [comment]
how do u use this btw i dont understand how it work

**Comment by Rushor** [comment]
what do you want to know in detail?

**Comment by blasterdude9** [comment]
how to get it to make the sql files for wow client 6.2.0.20338

**Comment by Rushor** [comment]
clone the repo, compile it, go to release or debug folder, copy .pkt file to folder, move .pkt-file with drag-and-drop over the .exe (remember to to add your sqldatas in the .config)

**Comment by blasterdude9** [comment]
i did that what else do i have to do

**Comment by blasterdude9** [comment]
what is wpp database

**Comment by Carbenium** [comment]
This is not a forum. Please move your conversation to http://community.trinitycore.org/

**Comment by blasterdude9** [comment]
i did and can post what i need to post at

**Comment by soulfrost** [comment]
are we still need `text` here? as i see broadcastTextID can be use ( ye, we cant get it from sniffs, but it can be simple compared with hotfix_db data )

**Comment by Killyana** [comment]
The '' is used because in some cases you can get multiple BroadcastTextID, you have to choose one that is in the correct range.
