### ISSUE TITLE
[6.2.2.-20444] Determined Fields/Tables dont exist more

### ISSUE THREAD

**Issue by Daniel25** [TrinityCore/WowPacketParser#209]
latest commit b6cf88e013

In the output to sql any fields need to be deleted:

In creatures table field phasemask wouldnt exist.
In gameobject table field phasemask wouldnt exist.
ObjectNames table wouldnt exist.
weather_updates table wouldnt exist.
creature_movement table wouldnt exist.
 creature_text fields groupid and id fields are padded always with a "x" instead of his real valor.
 npc_spellclick_spells cast_flags and user_type fields are padded with a "x" instead of his real valor.
In creature_template table fields questitem1,questitem2,questitem3,questitem4,questitem5,questitem6 wouldnt exist.

**Comment by DDuarte** [comment]
What?

**Comment by Daniel25** [comment]
When you use the parsser, the sql file output show fields which doesnt exist in TC DB.

**Comment by DDuarte** [comment]
Fuck...  I thought this was an issue on the TrinityCore repo, not WPP. Sorry

**Comment by Daniel25** [comment]
No problem.Sorry I did explain it bad...Any fields need to be deleted in the output of sql (my english is really poor).

**Comment by BAndysc** [comment]
"creature_text fields groupid and id fields are padded always with a "x" instead of his real valor."
Because it is up to you to choose group id and id since it cannot be done automatically. Parser do not know whether the dialogue should go to the same group id or it is completely different speech

**Comment by sujezz** [comment]
Any chance on update to 6.2.2 ?

**Comment by Carbenium** [comment]
Take a look here: https://github.com/TrinityCore/WowPacketParser/tree/sql_rewrite
This will be merged soon.

**Comment by Carbenium** [comment]
Closed with 3ddbce572bddaf79c3d570cf406cc98d927acbad
