### ISSUE TITLE
[CRASH] when Sniffing Data

### ISSUE THREAD

**Issue by Ahtuno** [TrinityCore/WowPacketParser#214]
Rev: 097e982544f45866f302587f4d453f4aee87746a

http://prntscr.com/907moc

---

Loading module WowPacketParserModule.V6_0_2_19033.dll
[1/1 20574_2015-11-07_21-44-43_01E3684D.pkt]: Parsing 10MB of packets. Detected version V6_2_2a_20574
[1/1 20574_2015-11-07_21-44-43_01E3684D.pkt]: Saved file to 'C:\Program Files\World of Warcraft\20574_2015-11-07_21-44-43_01E3684D_parsed.txt'
[1/1 20574_2015-11-07_21-44-43_01E3684D.pkt]: Parsed 76095 (99.951%) packets successfully, 17 (0.022%) with errors and skipped 19 (0.025%) without structure 1 (0.001%)  (total: 76132) in 00:00:17.487
1/76 - Write HotfixData
2/76 - Write AreaPOI
3/76 - Write AreaPOIState
4/76 - Write BattlePetSpecies
5/76 - Write BroadcastText
6/76 - Write ChrUpgradeTier
7/76 - Write ChrUpgradeBucket
8/76 - Write ChrUpgradeBucketSpell
9/76 - Write Creature
10/76 - Write CreatureDifficulty
11/76 - Write CurvePoint
12/76 - Write HolidayData
13/76 - Write Item
14/76 - Write ItemAppearance
15/76 - Write ItemBonus
16/76 - Write ItemBonusTreeNode
17/76 - Write ItemCurrencyCost
18/76 - Write ItemEffect
19/76 - Write ItemExtendedCost
20/76 - Write ItemModifiedAppearance
21/76 - Write ItemSparse
22/76 - Write GameObjects
23/76 - Write KeyChain
24/76 - Write Location
25/76 - Write Mount
26/76 - Write OverrideSpellData
27/76 - Write PhaseXPhaseGroup
28/76 - Write SceneScript
29/76 - Write SpellAuraRestrictions
30/76 - Write SpellCastingRequirements
31/76 - Write SpellClassOptions
32/76 - Write SpellEffectGroupSize
33/76 - Write SpellLearnSpell
34/76 - Write SpellMisc
35/76 - Write SpellPower
36/76 - Write SpellReagents
37/76 - Write SpellTotems
38/76 - Write Toy
39/76 - Write BroadcastTextLocale
40/76 - Write LocalesQuest
41/76 - Write LocalesQuestObjectives
42/76 - Write StartInformation
43/76 - Write ObjectNames
44/76 - Write SniffData
... then crash

**Comment by Carbenium** [comment]
Jump on our IRC channel #trinity @ irc.rizon.net so we can sort this out :)

**Comment by Carbenium** [comment]
Sorted things out in IRC. User was using a rev from the unstable sql_rewrite branch.
