### ISSUE TITLE
Creature_equip_template missmatch

### ISSUE THREAD

**Issue by msoky** [TrinityCore/WowPacketParser#229]
VerifiedBuild of sniffs is 20886
revision https://github.com/TrinityCore/WowPacketParser/commit/5fcf5309b9fcb91c0f025a5e877ab78690153f4d

There is problem with ItemID1 / ItemID2 / ItemID3
in sniffs, values from ItemID2 is MAYBE moved in ItemID3 and values ItemID3 probably in ItemID4 but this doesnt exist...OR bug is in OLD sniffs/parsers with VerifiedBuild 18019 and oldest

for example:
`creature_equip_template` (`CreatureID`, `ID`, `ItemID1`, `ItemID2`, `ItemID3`, `VerifiedBuild`) 

sniffs: (15938, 1, 24034, 0, 24034, 0);
TC:    (15938, 1, 24034, 24034, 5258, 18019);

which is right and which is wrong? wrong TC values or sniffer/parser

**Comment by msoky** [comment]
okay, in TC is wrong values...its from build 18019, i dont know who is sniffed, but he did wrong values...a LOT of wrong values along all creature equip template table...

**Comment by DDuarte** [comment]
Great?
