### ISSUE TITLE
Locale issue while parsing

### ISSUE THREAD

**Issue by LuigiElleBalotta** [TrinityCore/WowPacketParser#235]
I'm playing with itIT locale.
itIT locale names for creature and gameobject are used as update in *_template and not in *_template_locale

Also, some query contains the word "UNKNOWN", it breaks the query execution (at least in Heidi SQL, don't know in other programs). 
##

**Comment by Aokromes** [comment]
The 2nd not a bug.

**Comment by LuigiElleBalotta** [comment]
OK but the first yes.
If the second is not  a bug it is a SQL client issue?

**Comment by Aokromes** [comment]
No, the 2nd is intended.

**Comment by funjoker** [comment]
Fixed.
Issue was: Missing Config key and wrong flag for nullable names
