### ISSUE TITLE
Guids for creature and gameobject spawns are declared as strings instead of integers

### ISSUE THREAD

**Issue by Ovahlord** [TrinityCore/WowPacketParser#237]
The latest build (rev .: f08b18200ff96db61222c50820dcd0f366866f34 ) is parsing the sniffs as it should be. However, the sql output for spawns is having some issues:
- guids in the sql statements are being declared as strings instead of integers. (like: '@CGUID+0',...)
- phaseId's are not set to 1 by default so the raw sql output will throw errors due to the minimum required value = 1.
##

**Comment by funjoker** [comment]
Still not fixed

**Comment by funjoker** [comment]
Wasnt this issue fixed yet?

**Comment by funjoker** [comment]
Invalid
