### ISSUE TITLE
Random ignored packets

### ISSUE THREAD

**Issue by Ovahlord** [TrinityCore/WowPacketParser#241]
I was parsing some 21463 sniffs for my current iron docks scripts and while doing that I noticed that the parser is ignoring some packets completely random. 

Example: this is a sql output of the full run. If you know the dungeon you will see that there are A TON of missing texts:
Also the parsed text file does not contain the texts.
This issue applies on ObjectCreate packets so that some spawns are missing as well as broadcast texts and monster yells. Might also affect more of them.

```
INSERT INTO creature_text (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `comment`) VALUES
(83616, UNKNOWN, UNKNOWN, 'Yes, captain!', 14, 0, 100, UNKNOWN, 0, 44059, '85937', 'Zoggosh to Koramar'),
(81305, UNKNOWN, UNKNOWN, 'Warsong arrows sing from the sky! They''ll be the last thing you hear as I crush your skull.', 14, 0, 100, 396, 0, UNKNOWN, '85406', 'Fleshrender Nok''gar'),
(80808, UNKNOWN, UNKNOWN, 'You''d better step back. I''m calling in the Bombsquad!', 14, 0, 100, UNKNOWN, 0, UNKNOWN, '85417', 'Neesa Nox'),
(81432, UNKNOWN, UNKNOWN, 'You''ll never make it out alive!', 14, 0, 100, 603, 0, 43903, '86418', 'Grom''kar Technician to Player'),
(80805, UNKNOWN, UNKNOWN, 'You will burn!', 14, 0, 100, UNKNOWN, 0, 45801, '53513 - 85476', 'Makogg Emberblade'),
(80816, UNKNOWN, UNKNOWN, 'No! None shall possess my potency!', 14, 0, 100, UNKNOWN, 0, UNKNOWN, '85474', 'Ahri''ok Dugru to Player'),
(83613, UNKNOWN, UNKNOWN, 'FIRE... FIRE! AIM, THEN FIRE!', 14, 0, 100, 6, 0, 43903, '85910', 'Koramar to Player'),
(83578, UNKNOWN, UNKNOWN, 'CRUSH THEM!!!', 14, 0, 100, 480, 0, UNKNOWN, '85904', 'Ogron Laborer to Player'),
(83026, UNKNOWN, UNKNOWN, 'Get these war machines ready for the siege.', 12, 0, 100, 396, 0, UNKNOWN, '85397', 'Siegemaster Olugar');
```

**Comment by DDuarte** [comment]
Could you upload the pkt somewhere? Link here, message me on IRC (#trinity @ irc.rizon.net) or email. I'll take a look.

**Comment by Ovahlord** [comment]
Sure, here we go:  http://www.mediafire.com/download/ty99cpu6q7emre7/iron_docks_HC_hyper_fast.pkt

**Comment by Aokromes** [comment]
@Ovahlord i sugest you to delete the sniff asap blizzard can get it and ban you.

**Comment by Ovahlord** [comment]
Done, ty for pointing it out~

**Comment by Ovahlord** [comment]
After several packet research it appears that creature_texts are rarely being used. instead they use broadcast texts and their packets to schedule entire talk events by their own. A system that is currently not supported by the core so for now it not a issue, more a missing feature.
