### ISSUE TITLE
Older version of WPP?

### ISSUE THREAD

**Issue by ic3cr34m** [TrinityCore/WowPacketParser#243]
I should have been more clear in my last post, so I apologize.
What I'm looking for is an older version of WPP. I was watching this YouTube video: https://www.youtube.com/watch?v=GlhHJLtJJJ0 and the guy had a different wowpacketparser.exe.config file. It was totally a different layout.

I was hoping to get that since WPP is giving me issues while parsing for SQL files. It crashes or the SQL file isn't complete.

Again I apologize for not having enough information last time. Hopefully this is better.

**Comment by ic3cr34m** [comment]
This can be closed actually.
I didn't know you could still talk in closed issues.

**Comment by Aokromes** [comment]
This is not a forum
