### ISSUE TITLE
extract phase?

### ISSUE THREAD

**Issue by ProjectcoreDevs** [TrinityCore/WowPacketParser#247]
Hi, i want know, if we can extract the phase of creature and gameobject?
##

**Comment by Vincent-Michael** [comment]
client build?

**Comment by ProjectcoreDevs** [comment]
6x global

**Comment by ProjectcoreDevs** [comment]
in the tannan jungle i fund +10 phaseID ... then how extract it for each creature and gameobject?

**Comment by Ovahlord** [comment]
sniffs.

**Comment by funjoker** [comment]
You cant.
After Phase change you get an update opcode. Showing which creatures are destroyed and which are New. But only the creatures you can See.
This give you theoretically the Info you need. Its a Manual Job

**Comment by bozoweed** [comment]
Can you make a tuto for how to found all of that info and make manual patch ? May be the tuto in forum atlantis created by @BAnsync is great for that but not updated for new db architecture. 
I sayed you a big thanks for read that and maybe make a little tuto or big tuto like you want but really thank for trinity/atlantis team ! :D

**Comment by LuigiElleBalotta** [comment]
https://github.com/TrinityCore/WowPacketParser/pull/289
