### ISSUE TITLE
First letter is cut while parsing

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/WowPacketParser#249]
I tried to sniff a guard at Darnasus to get gossips and POI, I got this issue:

```
ServerToClient: SMSG_GOSSIP_POI (0x2752) Length: 38 ConnIdx: 1 Time: 06/24/2016 16:17:47.813 Number: 9633
Flags: -684684031 (-684684031)
Coordinates: X: -2.283941E+20 Y: 1.482769E-34
Icon: Blank (0)
Data: 1342177280
Icon Name: êche de Darnassus
```
``` sql
INSERT INTO points_of_interest (`ID`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Data`, `Name`, `VerifiedBuild`) VALUES
(38, -2.283941E+20, 1.482769E-34, 0, 3610283265, 1342177280, 'êche de Darnassus', 21742), -- 38
```
The first letter is cut it must be: Pêche de Darnassus
It's the case for all the POI, I don't know if this happen only with poi as the parser wasn't able to parse anything else.

**Comment by DDuarte** [comment]
Obviously wrong structure, it doesn't have anything to do with the text.

What build is it?

**Comment by Killyana** [comment]
rev https://github.com/TrinityCore/WowPacketParser/commit/51eb969edd86866f9ab5897e1e6aa1c675399c4e

**Comment by DDuarte** [comment]
Cannot reproduce.

```
ServerToClient: SMSG_GOSSIP_POI (0x2752) Length: 38 ConnIdx: 1 Time: 06/24/2016 15:17:47.813 Number: 9633
Flags: 99
Coordinates: X: 9836.21 Y: 2432.18
Icon: RedFlag (7)
Importance: 0
Name: Pêche de Darnassus
```

**Comment by Killyana** [comment]
I tried with the pre-compiled version https://ci.appveyor.com/api/projects/DDuarte/wowpacketparser-191/artifacts/WowPacketParser/WPP.zip?job=Configuration:%20Release and every thing looks good.
