### ISSUE TITLE
item_template sql bad made

### ISSUE THREAD

**Issue by JoNMii** [TrinityCore/WowPacketParser#252]
At the moment isnt making god sql for item_template.
It isnt adding al values to the query, also the order for spell camps and other arent the same
I cant manage to find the issue

**Comment by lorac2k14** [comment]
If this was posted 10 days ago the parser falls under the https://github.com/TrinityCore/WowPacketParser/commit/c76b831060a48876f13edafb60f3eae928d644dc commit try pulling new commit ... not sure if it is fixed yet but it was announced in the commit no parsing

**Comment by Aokromes** [comment]
You don't specify what version is the sniff you have tried to parse, nor the database target you selected.

**Comment by Carbenium** [comment]
Closing for now. If more information is added we can reopen the issue.

**Comment by JoNMii** [comment]
335 Database and 335sniff

**Comment by lorac2k14** [comment]
how are you getting accurate 3.3.5a sniffs there is no retail 3.3.5a to be accessed  just curious
