### ISSUE TITLE
7.0.3 SMSG_UPDATE_OBJECT System.IO.EndOfStreamException (Part 2)

### ISSUE THREAD

**Issue by OrzelBialy** [TrinityCore/WowPacketParser#254]
**Description**: SMSG_UPDATE_OBJECT again. (module V7_0_3_22248) System.IO.EndOfStreamException when parsing

**Steps to reproduce the problem**:

1. Download this file: http://www73.zippyshare.com/v/2NFo9Wqo/file.html
2. Run the file through WPP
3. Look at packet number 188

**WPP hash/commit**:  68943eb5031a6afc9270590223508538f760e945

**Operating system**:  Win10 64bit

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by jcmillions** [comment]
I am still getting this issue.

**Comment by Vincent-Michael** [comment]
You have sniff with broken data?

**Comment by jcmillions** [comment]
It gives me the following error int the command prompt window:
GuildMemberFlag has undefined flags: Unk10, Unk 40
QuestFlags2 has undefined flags: Unk10000

**Comment by jcmillions** [comment]
[2016_09_01_00_04_37_log.txt](https://github.com/TrinityCore/WowPacketParser/files/448852/2016_09_01_00_04_37_log.txt)
