### ISSUE TITLE
[6.x] value UNKNOWN

### ISSUE THREAD

**Issue by bozoweed** [TrinityCore/WowPacketParser#264]
In some db from world like "creature" we got some value UNKOWN like trainer_type etc..  how fix that ?
##

**Comment by BAndysc** [comment]
Fill those values yourself, as they cannot be extracted from sniff (or they would have to be guessed what would produce invalid value sometimes)

**Comment by Aokromes** [comment]
Or they need additional sniffs to get proper values.

**Comment by bozoweed** [comment]
okey . so for exemple the master xin in starter zone of pandaria need to be fix manualy by me ?
but can be also fix by more sniff and "stack" all my sniff in one pkt file ?

**Comment by bozoweed** [comment]
I will work on this and.try to see also thank you for  your help . :)
