### ISSUE TITLE
[6.x] idee make tuto for manual patching

### ISSUE THREAD

**Issue by bozoweed** [TrinityCore/WowPacketParser#267]
Hi trinity's team 

Can you make a tuto for how to found all of that info and make manual patch ? May be the tuto in forum atlantis created by @BAnsync is great for that but not updated for new db architecture. 
I sayed you a big thanks for read that and maybe make a little tuto or big tuto like you want but really thank for trinity/atlantis team ! :D

Ps: i think this is a great idee because more we are to know how to do this , more update can be PR in trinitycore ans then make the best db ever for the core the parsed.txt can help the de  to make more update to .

**Comment by DDuarte** [comment]
Thanks for the suggestion but we are not currently interested in it.

**Comment by bozoweed** [comment]
Ok no problem thanks for your answer
