### ISSUE TITLE
[6.x/7.x] scene_template Output

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/WowPacketParser#268]
Due to this commit:
https://github.com/TrinityCore/TrinityCore/commit/d4887311e39527e036419ebd966f399fdbdae67a

There is a need to parse and make fitting SQL of SMSG_PLAY_SCENE.

CREATE TABLE `scene_template` (
`SceneId` int(10) unsigned NOT NULL,
`Flags` int(10) unsigned NOT NULL DEFAULT '0',
`ScriptPackageID` int(10) unsigned NOT NULL DEFAULT '0',
`ScriptName` varchar(64) NOT NULL DEFAULT '',
PRIMARY KEY (`SceneId`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
##

**Comment by joschiwald** [comment]
fixed in fbef939c03f54b617595db4ee166df2e015f160b
