### ISSUE TITLE
It does not create a SQL file.

### ISSUE THREAD

**Issue by diavolb** [TrinityCore/WowPacketParser#276]
When disassembling Sniff file is created only a .txt file, but to create an SQL file does not want to.
![8urn65u](https://cloud.githubusercontent.com/assets/3106386/20590798/5683cfd0-b236-11e6-9092-62a8453f5a38.png)

        <add key="DumpFormat" value="1"/>
        <add key="creature"                         value="true"/>
        <add key="creature_addon"                   value="false"/>
        <add key="creature_equip_template"          value="true"/>
        <add key="creature_model_info"              value="true"/>
        <add key="creature_template"                value="true"/>
        <add key="creature_template_addon"          value="true"/>
        <add key="creature_text"                    value="true"/>
        <add key="gameobject"                       value="true"/>
        <add key="gameobject_addon"                 value="false"/>
        <add key="gameobject_template"              value="false"/>
        <add key="gameobject_template_addon"        value="false"/>
        <add key="gossip_menu"                      value="true"/>
        <add key="gossip_menu_option"               value="true"/>
        <add key="item_template"                    value="false"/>
        <add key="locales_quest"                    value="true"/>
        <add key="locales_quest_objectives"         value="true"/>
        <add key="npc_spellclick_spells"            value="true"/>
        <add key="npc_text"                         value="true"/>
        <add key="npc_trainer"                      value="true"/>
        <add key="npc_vendor"                       value="true"/>
        <add key="ObjectNames"                      value="false"/>
        <add key="page_text"                        value="true"/>
        <add key="playercreateinfo"                 value="false"/>
        <add key="playercreateinfo_action"          value="false"/>
        <add key="points_of_interest"               value="false"/>
        <add key="quest_poi"                        value="false"/>
        <add key="quest_poi_points"                 value="false"/>
        <add key="quest_template"                   value="false"/>
        <add key="SniffData"                        value="false"/>
        <add key="SniffDataOpcodes"                 value="false"/>
        <add key="vehicle_template_accessory"       value="false"/>
        <add key="weather_updates"                  value="false"/>
        <add key="hotfix_data"                      value="true"/>

What could be the problem?

**Comment by diavolb** [comment]
It was decided, were not connected to a dll.

**Comment by DDuarte** [comment]
Is this an issue?

**Comment by Aokromes** [comment]
no answer after 3 months, closing.
