### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by Atis6** [TrinityCore/WowPacketParser#277]
Need to implement:
creates scenario_poi
scenario_poi_points

**Comment by DDuarte** [comment]
A little more info would be useful.

**Comment by Krudor** [comment]
We need to add handlers for the scenario opcodes and export scenario poi data from sniffs into our new scenario poi table (TrinityCore master branch).
I should probably be the to add this but I've got a few other things I need to finish before I can start on this.

If anyone's got some free time on their hands, be my guest.

**Comment by funjoker** [comment]
Included at #369

https://github.com/TrinityCore/WowPacketParser/pull/369/commits/b22fa76342498268071ea1b3ba3adb667d8300c5
