### ISSUE TITLE
`creature_text` table can only output 1 text per creature

### ISSUE THREAD

**Issue by Krudor** [TrinityCore/WowPacketParser#278]
Title.
The output SQL file always contain only 1 text per creature entry, when there should be more, if the creature has spoken more than once.

**Comment by joschiwald** [comment]
it is because of the primary key set in wpp

**Comment by Krudor** [comment]
Appears to be fixed now

**Comment by Krudor** [comment]
Can't find the commit fixing this issue.

**Comment by funjoker** [comment]
was prolly just a sideeffect fix or bug ^^
