### ISSUE TITLE
Port WPP to .NET Core/Standard

### ISSUE THREAD

**Issue by LuigiElleBalotta** [TrinityCore/WowPacketParser#292]
Why not converting WoWPacketParser from .NET Framework to .NET Core? So it will be cross platform.

It should be a great thing to do a cross-platform sniffer too!

**Comment by Aokromes** [comment]
you can use it on linux already.

**Comment by Shauren** [comment]
sniffer? not happening, it uses low level system apis and needs to be specialized for each platform (win x86, win x64), linux has no wow binary so you use wine (and WSTC works with wine too)

**Comment by LuigiElleBalotta** [comment]
@Shauren  ok i didn't know that sorry
@Aokromes and Shauren: what about Mac OS X?

**Comment by Shauren** [comment]
Also not happening, I'm not going to bother with learning mac api, and setting up a mac vm to compile/test it
Also while not amazing, you can use windows wow executable on mac together with wtsc and wine

**Comment by LuigiElleBalotta** [comment]
I'm talking about WoWPacketParser in .NET CORE. You can test on Windows, if work on windows it will work on Mac too. The compiler is the same.

**Comment by Aokromes** [comment]
If you can use it on linux, it's very likely you can use it on macos.

**Comment by LuigiElleBalotta** [comment]
I'm going to test, i will give you feedback as soon as i can

**Comment by LuigiElleBalotta** [comment]
Compiles under mac too... Btw net core is newer, it should be taken in consideration to move that way

**Comment by DDuarte** [comment]
Supporting .Net core is in my roadmap

**Comment by zamalaev** [comment]
sniffer x86 sees Warden
sniffer x64 no problem

bad my english

**Comment by DDuarte** [comment]
This has nothing to do with sniffers.

**Comment by DDuarte** [comment]
Result of [.NET Portability Analyzer](https://github.com/Microsoft/dotnet-apiport):

![image](https://cloud.githubusercontent.com/assets/530940/24334859/7ae25a88-126a-11e7-96c6-6928e17091d2.png)

![image](https://cloud.githubusercontent.com/assets/530940/24334850/40e74eba-126a-11e7-9bac-a7cf66e211ab.png)
