### ISSUE TITLE
Error New Client Version 7.2.0 23857 For WPP

### ISSUE THREAD

**Issue by Taaboy** [TrinityCore/WowPacketParser#299]
Not to Nag,  But we do need a update

Great Work

**Comment by Vincent-Michael** [comment]
soon

**Comment by Taaboy** [comment]
Thank You  any PKT file you require.

**Comment by Luchass** [comment]
I look forward to it.

**Comment by Luchass** [comment]
It doesn't work properly. WPP can't read a lot of packets.

ServerToClient: 11682 (0x2DA2) Length: 111 ConnIdx: 1 Time: 04/02/2017 21:18:22.762 Number: 486
|-------------------------------------------------|---------------------------------|
| 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F | 0 1 2 3 4 5 6 7 8 9 A B C D E F |
|-------------------------------------------------|---------------------------------|
| 2F FF 24 48 5F 01 13 80 7F 1D 60 47 70 1F 20 81 | / . $ H _ . . .  . ` G p .   . |
| 2E C6 45 5C 89 43 40 24 BC CE 43 0C 3E 1E 06 00 | . . E \ . C @ $ . . C . > . . . |
| 00 00 00 00 00 00 00 00 00 00 00 00 00 00 30 00 | . . . . . . . . . . . . . . 0 . |
| 00 00 00 00 00 00 00 00 00 E8 16 00 00 00 00 00 | . . . . . . . . . . . . . . . . |
| 00 00 00 00 00 00 00 00 00 00 00 00 40 01 40 CA | . . . . . . . . . . . . @ . @ . |
| C6 C5 45 B0 56 5E 40 5D 66 CB 43 F2 07 40 FE FA | . . E . V ^ @ ] f . C . . @ . . |
| 07 00 FF 01 00 C0 FF 09 00 80 00 15 F8 7F 02    | . . . . . . . . . . . . .  .   |
|-------------------------------------------------|---------------------------------|

**Comment by Vincent-Michael** [comment]
@Luchass 
soon ... only client opcodes are finish

**Comment by Luchass** [comment]
Ok

**Comment by Taaboy** [comment]
Nice Work guys, Thank You, Now all we need is the other part No pressure...lol

But Great Work
