### ISSUE TITLE
Unable to read beyond the end of the stream

### ISSUE THREAD

**Issue by Luchass** [TrinityCore/WowPacketParser#304]
When I try to make sql file for creature table or gameobject table, I get error "Unable to read beyond the end of the stream".
http://i.imgur.com/aUgwOdV.png

I checked it on two different computers and got the same error.

**Comment by Pveska** [comment]
Сonfirm, I have the same error.

**Comment by Vincent-Michael** [comment]
i can current no multi version ... wdb5 != 7.2.0

**Comment by Undergarun** [comment]
Maybe some kind of message like "Are you sure you are using 7.2.0 dbc version?" Will help us a lot. Just as a suggestion.

**Comment by Caydan** [comment]
I'm having the same issue. I've disabled DBC usage atm but compiling now the latest tools to extract the 7.2 dbfilesclient

**Comment by Caydan** [comment]
Alright. After I have extracted the latest dbc files all packets were parsed fine. But if you dont have extracted the latest dbcs you will get tons of thrown exceptions also if you have disabled the dbc usage.

**Comment by Luchass** [comment]
Any progress? Now I can't even make sql file for creature/gameobject with last dbc (7.2.5.24936).

**Comment by funjoker** [comment]
Same as #317 
Can be closed

**Comment by Aokromes** [comment]
d980e72b130e5cf2d336d1bdf9d92db07c7314a3
