### ISSUE TITLE
Missing Templates WPP

### ISSUE THREAD

**Issue by Taaboy** [TrinityCore/WowPacketParser#306]
8945062 commit 9f620df5af6bb233499d4b35d3d82a2d6194ed13 

This maybe on purpose, but i can't see on extraction quest_template , quest_objectives and quest_visual_effects.
Used a previous version on WPP Master Version and they show up under the extracted SQL, but current version they are missing. I used same PKT file on both version  and same setting then sniffed pkt is from Version 7.1.5 _23420 and missing templates outputs.

TAABOY

**Comment by Aokromes** [comment]
you get any error?

**Comment by Taaboy** [comment]
no

**Comment by Taaboy** [comment]
1 sec i will turn on error log also

**Comment by Taaboy** [comment]
[Pandaren start_errors.txt](https://github.com/TrinityCore/WowPacketParser/files/951895/Pandaren.start_errors.txt)
[2017_04_24_23_43_04_log.txt](https://github.com/TrinityCore/WowPacketParser/files/951896/2017_04_24_23_43_04_log.txt)

**Comment by Taaboy** [comment]
[2017_04_24_23_49_17_log_WPP_12_3_17_Version.txt](https://github.com/TrinityCore/WowPacketParser/files/951929/2017_04_24_23_49_17_log_WPP_12_3_17_Version.txt)
[Pandaren start_errors_WPP_12_3_17_Version.txt](https://github.com/TrinityCore/WowPacketParser/files/951926/Pandaren.start_errors_WPP_12_3_17_Version.txt)
WPP Version Release 12_3_17 same PKT

**Comment by Taaboy** [comment]
found the error, it is not being turn on when you set true to quest_template on its own and know other choices made, sorry , upon turning on all choices to true , minus the opcodes and hotfixdata it shows up.

Funny , maybe something is a miss, but works on the old version with quest_template turned on.

**Comment by Kodekc** [comment]
Confirmed

**Comment by funjoker** [comment]
> [Pandaren start_errors.txt](https://github.com/TrinityCore/WowPacketParser/files/951895/Pandaren.start_errors.txt)
> [2017_04_24_23_43_04_log.txt](https://github.com/TrinityCore/WowPacketParser/files/951896/2017_04_24_23_43_04_log.txt)
> From latest WPP Release

SMSG_QUEST_GIVER_QUEST_DETAILS

**Comment by funjoker** [comment]
gonna take a look

**Comment by funjoker** [comment]
i can't reproduce
