### ISSUE TITLE
SQL error on broadcast_text load from hotfixes.

### ISSUE THREAD

**Issue by Undergarun** [TrinityCore/WowPacketParser#307]
Connecting to MySQL server: Server=localhost;Port=3306;Username=root;Database=wp
p;CharSet=utf8;ConnectionTimeout=5;
Table 'worldofwarcraft_hotfixes715.broadcast_text' doesn't exist at query "SELEC
T ID, MaleText, FemaleText, EmoteID1, EmoteID2, EmoteID3, EmoteDelay1, EmoteDela
y2, EmoteDelay3, UnkEmoteID, Language, Type, SoundID1, SoundID2, PlayerCondition
ID FROM worldofwarcraft_hotfixes715.broadcast_text;"
SQL loaded in 00:00:00.000.

WPP: latest 9f620df5af6bb233499d4b35d3d82a2d6194ed13
Hotfix base: TDB_hotfixes_703.00_2016_10_17.sql

Of course i checked that database exists.

**Comment by Taaboy** [comment]
Ok i have seen this a few times , and if i remember , it happens when there is no DB to confirm too,

```
        <!-- Database settings -->
        <add key="DBEnabled"          value="true" />
        <add key="Server"             value="localhost" />
        <add key="Port"               value="3306" />
        <add key="Username"           value="root" />
        <add key="Password"           value="ascent" />
        <add key="WPPDatabase"        value="wpp" />
        <add key="TDBDatabase"        value="world" />
        <add key="HotfixesDatabase"   value="hotfixes" />
        <add key="CharacterSet"       value="utf8" />
```
So yours should look similar to this and i don't get that error , i only get that error when db is turned on and not looking to a DB.
But that is the problem i have had, maybe different to your's

TAABOY

**Comment by Undergarun** [comment]
Note: Not happens if you have setted use DBC to true

**Comment by Undergarun** [comment]
Note, I am stupid. Thank you.
