### ISSUE TITLE
Issue attempting to read DBCs

### ISSUE THREAD

**Issue by Undergarun** [TrinityCore/WowPacketParser#308]
20/44 - Error: Failed writing Creature
WowPacketParser.exe Error: 0 : System.TypeInitializationException: Se produjo un
a excepción en el inicializador de tipo de 'WowPacketParser.DBC.DBC'. ---> Syste
m.IO.EndOfStreamException: No se puede leer más allá del final de la secuencia.
   en System.IO.BinaryReader.ReadByte()
   en DBFilesClient.NET.Reader`1.ReadInlineString()
   en DBFilesClient.NET.Reader`1.ReadTableString()
   en DBFilesClient.NET.WDB5.Reader`1.ReadTableString()
   en lambda_method(Closure , Reader`1 )
   en DBFilesClient.NET.WDB5.Reader`1.LoadRecord(Int64 recordPosition, Int32 key
, Boolean forceKey)
   en DBFilesClient.NET.WDB5.Reader`1.LoadRecords()
   en DBFilesClient.NET.Reader`1.Load()
   en DBFilesClient.NET.Storage`1.FromStream(Stream dataStream)
   en DBFilesClient.NET.Storage`1..ctor(String fileName, Boolean readOnly)
   en WowPacketParser.DBC.DBC..cctor() en E:\Git\WorldOfWarcraft\TrinityCore.Wow
PacketParser\WowPacketParser\DBC\DBC.cs:línea 24
   --- Fin del seguimiento de la pila de la excepción interna ---
   en WowPacketParser.Store.Objects.WoWObject.GetDefaultSpawnMask() en E:\Git\Wo
rldOfWarcraft\TrinityCore.WowPacketParser\WowPacketParser\Store\Objects\WoWObjec
t.cs:línea 73
   en WowPacketParser.SQL.Builders.Spawns.Creature(Dictionary`2 units) en E:\Git
\WorldOfWarcraft\TrinityCore.WowPacketParser\WowPacketParser\SQL\Builders\Spawns
.cs:línea 102

i located dbcs in /dbc/enUS/

**Comment by Aokromes** [comment]
#304
