### ISSUE TITLE
Some issues with 7.2.0.23937 writing AreaTriggerTemplateVerticesData

### ISSUE THREAD

**Issue by Undergarun** [TrinityCore/WowPacketParser#310]
2/44 - Error: Failed writing AreaTriggerTemplateVerticesData
WowPacketParser.exe Error: 0 : System.InvalidCastException: No se puede converti
r un objeto DBNull en otros tipos.
   en System.DBNull.System.IConvertible.ToSingle(IFormatProvider provider)
   en System.Convert.ChangeType(Object value, Type conversionType, IFormatProvid
er provider)
   en WowPacketParser.SQL.SQLDatabase.Get[T](RowList`1 rowList, String database)
 en E:\Git\WorldOfWarcraft\TrinityCore.WowPacketParser\WowPacketParser\SQL\SQLDa
tabase.cs:línea 204
   en WowPacketParser.SQL.Builders.AreaTriggers.AreaTriggerTemplateVerticesData(
) en E:\Git\WorldOfWarcraft\TrinityCore.WowPacketParser\WowPacketParser\SQL\Buil
ders\AreaTriggers.cs:línea 38

**Comment by Deaenerys** [comment]
I have the same problem

**Comment by osleyder85** [comment]
This error has already been resolved: [Pull: 464](https://github.com/TrinityCore/WowPacketParser/pull/464)
