### ISSUE TITLE
reading out of packet stream in parsing SMSG_QUEST_GIVER_QUEST_LIST_MESSAGE 

### ISSUE THREAD

**Issue by gpn39f** [TrinityCore/WowPacketParser#323]
WPP file hash 8c693a3  
File: QuestHandler.cs  hash: 423fb91  10 days ago @funjoker Add Parsring of ObjectiveOrder

failure in reading gossip text. 
message: reading out of memory stream
fresh sniff 7.2.5. 24461, Server EU, Language German

in function:
            public static void ReadGossipText(Packet packet, params object[] indexes)
in Line:
            var guestTitleLen = packet.ReadBits(9);

the reading size of 9 bit length is wrong.
should be 8.

**Comment by gpn39f** [comment]
it's long time ago, i have worked with assembler..
but what i see is: he build the length in 2 step.
he take first part in line 103 >> 8 bit 
and in line 104 >> 1 bit
and compute both to the needed length info..
if v9 and v14 point to different places, then i ask: can you simplify the formula and take 9 bit from first place ??

but i see that the length is * 2 in line 103..
and this result in a length outside the memory..
so i ask: are the client store strings in utf8 or as 2 byte char values??

**Comment by funjoker** [comment]
I checked 7.1.5 to 7.3.0.

```
  v10 = 2 * CDataStore::GetBits8(&v14, v9);
  v11 = v10 | CDataStore::GetBit(&v14);
  *(_DWORD *)((char *)v13 + 13) = v11;
  result = CDataStore::GetWoWString((char *)v13 + 13, v11);
```

its always 9 bits.
