### ISSUE TITLE
Parser creating blank .txt

### ISSUE THREAD

**Issue by Necrovoice** [TrinityCore/WowPacketParser#328]
Hello, i wanted to try my luck at this. However, when i try and use this with the latest trinity sniff (again my first attempt)  the .pkt file creats a blank txt file when used with the parser.  Am i doing somethi g wrong, or is something broke?

**Comment by Aokromes** [comment]
test https://github.com/TrinityCore/WowPacketParser/pull/327

**Comment by Necrovoice** [comment]
Ty for the quick responce :)
