### ISSUE TITLE
Missing gossip_menu_option_trainer in wpp

### ISSUE THREAD

**Issue by AussieGlenn** [TrinityCore/WowPacketParser#329]
Hi,

The new tables trainer and trainer_spells do not work by themselves, but need to be linked to the Missing gossip_menu_option_trainer table.

However, this table is not being extracted.

There is no way to fix trainers other than manual linking and guessing.

Thanks,

Glenn

**Comment by AussieGlenn** [comment]
Thanks so much :)

**Comment by buenodart** [comment]
Hey AussieGlenn

Did u make the alterations for trainer come works?
Can you help me with this?

I read the solution but I dont know how to do it!

Thanks =)
