### ISSUE TITLE
Latest build extracts incorrect tables for npc_trainer

### ISSUE THREAD

**Issue by AussieGlenn** [TrinityCore/WowPacketParser#330]
Hi,

When extracting the latest build, it had the table npc_trainer which no longer exists.

It also does not fill in the tables necessary to link the trainer and the spells they teach.

thanks,

Glenn

**Comment by Shauren** [comment]
It entirely depends on which version the sniff was made
Only 5.3.0, 5.4.1, 5.4.2, 5.4.7, 5.4.8, 6.x and 7.x sniff will output new tables, anything else will either not do anything or use `npc_trainer`

**Comment by AussieGlenn** [comment]
Hi Shauren,

It is possible I am making a mistake.

However, in void ObjectMgr::LoadTrainers() line 8520 in ObjectMgr.cpp it loads from the trainer_spell table.

It seems to me that the SQL for trainer_spell has been removed in the latest patch, meaning that it cannot be sniffed or obtained by any source.

Also, the table gossip_menu_option_trainer is referenced in void ObjectMgr::LoadGossipMenuItems() line 8787 which is also not available in Wowpacketparser or by any other source.

These two tables are used by the code to crossreference trainers and their spells.

Without sniffs for either of these tables, then the trainers do not work.

Again, it is entirely possible I am making an error, but it appears that the TC core requires trainer_spell and gossip_menu_option_trainer tables, and these tables are not available in the config to output.

Trainer_spell was there, but was removed, and gossip_menu_option_trainer was never available.

My sniff header is:

# TrinityCore - WowPacketParser
# File name: 24742_2017-08-18_20-19-01.pkt
# Detected build: V7_2_5_24742
# Detected locale: enUS
# Targeted database: Legion
# Parsing date: 08/21/2017 23:02:21

Thanks,

Glenn

**Comment by Shauren** [comment]
`trainer` config outputs `trainer`, `trainer_spell` and `creature_default_trainer` tables (grouped together because they don't make sense to be separated
Similarly,
`gossip_menu_option` config controls `gossip_menu_option`, `gossip_menu_option_action`, `gossip_menu_option_box` and `gossip_menu_option_trainer`

**Comment by buenodart** [comment]
Hi... anyone have the sql output for trainer come work?
Thanks

**Comment by funjoker** [comment]
Trainer works
