### ISSUE TITLE
Crash "InvalidCastException" with DB connected

### ISSUE THREAD

**Issue by DoctorKraft** [TrinityCore/WowPacketParser#331]
Hey, i have the parser connected to my DB with DB2
But per moment some binary sniff are totally broken, impossible to extract SQL
No crash, only one message "InvalidCastException" etc...

Here message :
**https://gist.github.com/DoctorKraft/66e633adc14eaa0fb12e4c8b3638219a**

**Comment by funjoker** [comment]
Hackfix:
Store/Objects/Unit.cs
Change this:
`UpdateFields.GetValue<UnitField, int>(UnitField.UNIT_FIELD_SCALING_LEVEL_DELTA);`

to this:
`UpdateFields.GetValue<UnitField, uint>(UnitField.UNIT_FIELD_SCALING_LEVEL_DELTA);`

And all accordings to this.

Joschi says: UNIT_FIELD_SCALING_LEVEL_DELTA can be negative.
I've never seen it.

**Comment by DoctorKraft** [comment]
Yeah i have also never found a negative value, it's always 1, 2 or 3 not more

**Comment by zgn1988** [comment]
` diff --git a/WowPacketParser/Store/Objects/CreatureTemplateScaling.cs b/WowPacketParser/Store/Objects/CreatureTemplateScaling.cs
index 85c9ee63..46ff88ed 100644
--- a/WowPacketParser/Store/Objects/CreatureTemplateScaling.cs
+++ b/WowPacketParser/Store/Objects/CreatureTemplateScaling.cs
@@ -16,7 +16,7 @@ namespace WowPacketParser.Store.Objects
         public uint? LevelScalingMax;
 
         [DBFieldName("LevelScalingDelta")]
-        public int? LevelScalingDelta;
+        public uint? LevelScalingDelta;
 
         [DBFieldName("VerifiedBuild")]
         public int? VerifiedBuild = ClientVersion.BuildInt;
diff --git a/WowPacketParser/Store/Objects/Unit.cs b/WowPacketParser/Store/Objects/Unit.cs
index 757d4641..76058111 100644
--- a/WowPacketParser/Store/Objects/Unit.cs
+++ b/WowPacketParser/Store/Objects/Unit.cs
@@ -134,14 +134,15 @@ namespace WowPacketParser.Store.Objects
             {
                 ScalingMinLevel = UpdateFields.GetValue<UnitField, uint?>(UnitField.UNIT_FIELD_SCALING_LEVEL_MIN);
                 ScalingMaxLevel = UpdateFields.GetValue<UnitField, uint?>(UnitField.UNIT_FIELD_SCALING_LEVEL_MAX);
+                ScalingDelta    = UpdateFields.GetValue<UnitField, uint?>(UnitField.UNIT_FIELD_SCALING_LEVEL_DELTA);
 
-                if (ScalingMinLevel != null && ScalingMaxLevel != null)
+                if (ScalingMinLevel != null && ScalingMaxLevel != null && ScalingDelta != null)
                 {
                     CreatureTemplateScaling creatureTemplateScaling = new CreatureTemplateScaling();
                     creatureTemplateScaling.Entry                   = UpdateFields.GetValue<ObjectField, uint>(ObjectField.OBJECT_FIELD_ENTRY);
                     creatureTemplateScaling.LevelScalingMin         = ScalingMinLevel;
                     creatureTemplateScaling.LevelScalingMax         = ScalingMaxLevel;
-                    creatureTemplateScaling.LevelScalingDelta       = UpdateFields.GetValue<UnitField, int>(UnitField.UNIT_FIELD_SCALING_LEVEL_DELTA);
+                    creatureTemplateScaling.LevelScalingDelta       = ScalingDelta;
                     Storage.CreatureTemplateScalings.Add(creatureTemplateScaling);
                 }
 
-- `

**Comment by zgn1988** [comment]
some fixed https://pastebin.com/s3beWQ7D

**Comment by Shauren** [comment]
d62d6108326b13c30e95d1540fa160502f1643a5
