### ISSUE TITLE
Error generating .sql from pkt files.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/WowPacketParser#332]
This is the log from cmd console in windows 10.

> D:\Juegos\Wow Cosas\Wod y Legion\Herramientas\Release>wowpacketparser.exe CostaAbrupta_23420_2017-03-15_22-55-47.pkt
> Loading module WowPacketParserModule.V6_0_2_19033.dll (fallback)
> Loading module WowPacketParserModule.V7_0_3_22248.dll
> [1/1 CostaAbrupta_23420_2017-03-15_22-55-47.pkt]: Parsing 94.8MB of packets. Detected version V7_1_5_23420
> Processing... 100% complete
> [1/1 CostaAbrupta_23420_2017-03-15_22-55-47.pkt]: Saved file to 'CostaAbrupta_23420_2017-03-15_22-55-47_parsed.txt'
> [1/1 CostaAbrupta_23420_2017-03-15_22-55-47.pkt]: Parsed 668244 (99.809%) packets successfully, 358 (0.053%) with errors, skipped 749 (0.112%) and without structure 171 (0.026%)  (total: 669522) in 00:00:51.947
> [1/1 CostaAbrupta_23420_2017-03-15_22-55-47.pkt] System.InvalidCastException
> [1/1 CostaAbrupta_23420_2017-03-15_22-55-47.pkt] La conversión especificada no es válida.
> [1/1 CostaAbrupta_23420_2017-03-15_22-55-47.pkt]    en WowPacketParser.Store.Objects.Ext.GetValue[T,TK](Dictionary`2 dict, T updateField) en C:\projects\wowpacketparser-191\WowPacketParser\Store\Objects\Unit.cs:línea 241
>    en WowPacketParser.Store.Objects.Unit.LoadValuesFromUpdateFields() en C:\projects\wowpacketparser-191\WowPacketParser\Store\Objects\Unit.cs:línea 144
>    en WowPacketParser.SQL.Builder.DumpSQL(String prefix, String fileName, String header) en C:\projects\wowpacketparser-191\WowPacketParser\SQL\Builder.cs:línea 88
>    en WowPacketParser.Loading.SniffFile.WriteSQLs() en C:\projects\wowpacketparser-191\WowPacketParser\Loading\SniffFile.cs:línea 519
>    en WowPacketParser.Loading.SniffFile.ProcessFileImpl() en C:\projects\wowpacketparser-191\WowPacketParser\Loading\SniffFile.cs:línea 272
>    en WowPacketParser.Loading.SniffFile.ProcessFile() en C:\projects\wowpacketparser-191\WowPacketParser\Loading\SniffFile.cs:línea 85

**Comment by zamalaev** [comment]
confirm

**Comment by Greymane** [comment]
Can confirm, no SQL files are being generated.

**Comment by DoctorKraft** [comment]
same problem, i have already opened a issue #331 

It's a problem with conversion of "LevelScalingDelta" because when you comment [this line](https://github.com/TrinityCore/WowPacketParser/commit/1aea02a789d163a6d48af41f477a832a6f52ccf6#diff-5f85460130b631a4dd56b4fa3d5b7690R144) it's works

@joschiwald maybe you have an idea?

**Comment by HannibalRoG** [comment]
What about this issue?

**Comment by funjoker** [comment]
uint int cast error...
I made a fix but joschi said it is wrong

**Comment by Aokromes** [comment]
#331
