### ISSUE TITLE
creature_text  output problem

### ISSUE THREAD

**Issue by soulfrost** [TrinityCore/WowPacketParser#347]
im using last wpp/hotfix databases and still got issue with creature_text, problem is in comparing of BroadcastTextId - it's `UNKNOWN` all time

```sql
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `comment`) VALUES
(115844, @GROUP_ID+0, @ID+, 'Чужаки! Я принесу ваши головы в дар повелителю!', 14, 0, 100, 0, 0, 85239, UNKNOWN, 'Горот to Player'),
(119726, @GROUP_ID+0, @ID+, 'Отступаем!', 14, 0, 100, 0, 0, 85239, UNKNOWN, 'Верховный маг Кадгар to Player');
```

**Comment by Ovahlord** [comment]
not a actual issue. looking up for those texts in db would make the parsing slow and bears the danger of getting a duplicate or wrong id when a text is identical. Needs manual correction

**Comment by soulfrost** [comment]
@Ovahlord it's actual, cos all text should use BroadcastTextIDs for translate on all langs, if it's slow - u can just turn off DB connection.

problem here that WPP looking just in broadcast_text table, so -it'll work just with enUS enGB sniffs in this case

**Comment by LuigiElleBalotta** [comment]
I Agree, it should be a user choice

**Comment by Aokromes** [comment]
Not a bug, intended.
