### ISSUE TITLE
Unknown BfA Opcode 0x2C3B

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/WowPacketParser#411]
0x2C3B is unnamed.

**Packets of 0x2C3B always appear right before SMSG_RESUME_CAST_BAR!**

```
        [Parser(Opcode.SMSG_SPELL_UNKNOWN_801)]
        public static void HandleSpellUnknown801(Packet packet)
        {
            packet.ReadPackedGuid128("CasterGUID");
            packet.ReadInt32("SpellXSpellVisualID");
            packet.ReadPackedGuid128("CastID");
            packet.ReadPackedGuid128("Target");
            packet.ReadInt32<SpellId>("SpellID");
        }
```

No idea what it is used for

**Comment by Shauren** [comment]
I researched a bit what it does - it sets SpellXSpellVisualID/CastID/Target/SpellID on CasterGUID unit to lookup SpellCast objects (basically, sets current cast identifier as client treats all four of these fields together as complete cast id)
Don't know anything more yet

**Comment by DoctorKraft** [comment]
Yeah it's mostly used by totems or summons with an animation at end of cast
For example:
[Static Charge (Shaman)](https://www.wowhead.com/spell=118905/static-charge)
[Spirit Drain (Dungeon)](https://www.wowhead.com/spell=265511/spirit-drain))

**Comment by funjoker** [comment]
it is **ALWAYS** before SMSG_RESUME_CAST_BAR <--------

**Comment by DoctorKraft** [comment]
And? I'm pretty sure it's related to https://github.com/TrinityCore/TrinityCore/issues/17886 but with SpellXSpellVisualID

**Comment by Mesielecat** [comment]
and when is used SMSG_RESUME_CAST_BAR ? Maybe is a preparation?

**Comment by Macsimka** [comment]
> 
> 
> And? I'm pretty sure it's related to [TrinityCore/TrinityCore#17886](https://github.com/TrinityCore/TrinityCore/issues/17886) but with SpellXSpellVisualID

Yes you are right.
SMSG_RESUME_CAST_BAR affect only cast bar (no visual part of cast). I think SMSG_SPELL_UNKNOWN_801 is needed for the visual part of the cast.

**Comment by funjoker** [comment]
This is: SMSG_RESUME_CAST
