### ISSUE TITLE
UpdateFieldType breaks parsing of old packets

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/WowPacketParser#434]
f5346fddf66f489c9fd0a099b4ad630ca57d5135

This breaks parsing of old packets.

Packet is not fully read when UpdateFieldType.Bytes is used

**Comment by funjoker** [comment]
```
[1] GUID: Full: 0x4300000306F8B19C Type: Item Low: 13001863580
[1] ITEM_END + 18: 0/0
[1] ITEM_END + 18: 208645095/1.846362E-31
[1] ITEM_END + 19: 0/0
```

2 times ITEM_END + 18 is this possible? 

if yes 

```
for (int k = 0; k < fieldData.Count; ++k)
                    dict.Add(start + k, fieldData[k]);
```

this will throw error

**Comment by killerwife** [comment]
Sounds like correct code but bad fields enum for version.

**Comment by funjoker** [comment]
checked enums, but they are correct

**Comment by funjoker** [comment]
Seems like the dictionary also broke the bytes part.

Works after fix like a charm

**Comment by funjoker** [comment]
unsure about the fields tbh
