### ISSUE TITLE
HotfixSerializer ulong

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/WowPacketParser#441]
Something is weird.

at ulong it skips 1 byte

**Comment by Warpten** [comment]
What does that even mean

**Comment by funjoker** [comment]
When parsing the hotfix response

Using a ulong in struct of hotfix, makes it skip the first byte for some reason.

That causes totally messed up values.

**Comment by funjoker** [comment]
For example part of some packet.

FF FF FF FF FF FF FF FF 4C 75 72 6B 65 72 27 73

Instead of reading FF FF FF FF FF FF FF FF

It reads FF FF FF FF FF FF FF 4C and ignores the first FF byte.

0x4CFFFFFFFFFFFFFF is incorrect then and mess up all other data

**Comment by Warpten** [comment]
Deserialization just calls methods from Packet, make sure reflection isnt returning propertied in incorrect order

**Comment by funjoker** [comment]
```
|-------------------------------------------------|---------------------------------|
| 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F | 0 1 2 3 4 5 6 7 8 9 A B C D E F |
|-------------------------------------------------|---------------------------------|
| FF FF FF FF FF FF FF FF 4C 75 72 6B 65 72 27 73 | . . . . . . . . L u r k e r ' s |
| 20 49 6E 73 69 64 69 6F 75 73 20 47 69 66 74 00 |   I n s i d i o u s   G i f t . |
| BA 8F 02 00 04 07 00 00 00 FF FF FF FF 78 00 00 | . . . . . . . . . . . . . x . . |
| 00 00 00 00 00 00 5E 01 00 00 08 00 00 20 00 00 | . . . . . . ^ . . . . . .   . . |
| 00 00 00 00 20 00 00 00                         | . . . .   . . .                 |
|-------------------------------------------------|---------------------------------|
```

That's the hex part of ItemSearchName.

It parses correctly with AllowableRace as long and incorrectly if it's ulong.

```
FF FF FF FF FF FF FF FF - AllowableRace
4C 75 72 6B 65 72 27 73 20 49 6E 73 69 64 69 6F 75 73 20 47 69 66 74 00 - Display
BA 8F 02 00 - ID
04 - OverallQualityID
07 - ExpansionID
00 00 - MinFactionID
00 - MinReputation
FF FF FF FF - AllowableClass
78 - RequiredLevel
00 00 - RequiredSkill
00 00 - RequiredSkillRank
00 00 00 00 - RequiredAbility
5E 01 - ItemLevel
00 00 08 00 - Flags1
00 20 00 00 - Flags2
00 00 00 00 - Flags3
20 00 00 00 - Flags4
```
Data which is parsed is correct.

**Comment by Warpten** [comment]
Oh this is a big yikes. Check that IHotfixSerializer<T> loads the proper method for uint64, and not the packed reader
