### ISSUE TITLE
8.1.0 SQL output.

### ISSUE THREAD

**Issue by updeal** [TrinityCore/WowPacketParser#448]
Why SQL output does not work on 8.1.0? I try 13 sniffs (8.1 patch) 29297,29139,28833 builds. But 8.1.5 sniffs work fine.

**Comment by funjoker** [comment]
UpdateFields 8.1 missing.

**Comment by updeal** [comment]
Ok

**Comment by vato312199** [comment]
still no fix info?

**Comment by xXBentRealityXx** [comment]
Oof, all of my sniffs are from 8.1

**Comment by mdX7** [comment]
UpdateFields for 8.1.0 are still missing, will work on that as soon as i have some time for that.

**Comment by xXBentRealityXx** [comment]
Any updates on this?

**Comment by mdX7** [comment]
Not yet, didn't have time for this yet.

**Comment by xXBentRealityXx** [comment]
Do you have a discord account I can contact you at? My username is Bent#1398
