### ISSUE TITLE
7.0.3.22522 Does not generate .sql file.

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/WowPacketParser#449]
WPP does not generate the sql file, this occurs with sniffer version 7.0.3 build 22522

**Comment by mdX7** [comment]
@osleyder85 which tables did you have enabled for sql parsing?

**Comment by osleyder85** [comment]
<add key="ObjectNames"                            value="true"/>
        <add key="SniffData"                              value="true"/>
        <add key="SniffDataOpcodes"                       value="true"/>

        <add key="areatrigger_template"                   value="true"/>
        <add key="areatrigger_template_polygon_vertices"  value="true"/>
        <add key="broadcast_text"                         value="true"/>
        <add key="broadcast_text_locale"                  value="true"/>
        <add key="conversation_actor_template"            value="true"/>
        <add key="conversation_actors"                    value="true"/>
        <add key="conversation_line_template"             value="true"/>
        <add key="conversation_template"                  value="true"/>
        <add key="creature"                               value="true"/>
        <add key="creature_addon"                         value="true"/>
        <add key="creature_equip_template"                value="true"/>
        <add key="creature_model_info"                    value="true"/>
        <add key="creature_template"                      value="true"/>
        <add key="creature_template_addon"                value="true"/>
        <add key="creature_template_locale"               value="true"/>
        <add key="creature_template_scaling"              value="true"/>
        <add key="creature_text"                          value="true"/>
        <add key="gameobject"                             value="true"/>
        <add key="gameobject_addon"                       value="true"/>
        <add key="gameobject_template"                    value="true"/>
        <add key="gameobject_template_addon"              value="true"/>
        <add key="gossip_menu"                            value="true"/>
        <add key="gossip_menu_option"                     value="true"/>
        <add key="item_template"                          value="true"/>
        <add key="locales_quest"                          value="true"/>
        <add key="locales_quest_objectives"               value="true"/>
        <add key="npc_spellclick_spells"                  value="true"/>
        <add key="npc_text"                               value="true"/>
        <add key="npc_trainer"                            value="true"/>
        <add key="npc_vendor"                             value="true"/>
        <add key="page_text"                              value="true"/>
        <add key="page_text_locale"                       value="true"/>
        <add key="playercreateinfo"                       value="true"/>
        <add key="playercreateinfo_action"                value="true"/>
        <add key="points_of_interest"                     value="true"/>
        <add key="quest_poi"                              value="true"/>
        <add key="quest_poi_points"                       value="true"/>
        <add key="quest_template"                         value="true"/>
        <add key="scene_template"                         value="true"/>
        <add key="scenario_poi"                           value="true"/>
        <add key="spell_target_position"                  value="true"/>
        <add key="spell_areatrigger"                      value="true"/>
        <add key="trainer"                                value="true"/>
        <add key="vehicle_template_accessory"             value="true"/>
        <add key="weather_updates"                        value="true"/>

        <add key="hotfix_data"                            value="true"/>
        <add key="hotfix_blob"                            value="true"/>

**Comment by osleyder85** [comment]
<add key="TargetedDatabase" value="5"/>

        
        <add key="DumpFormat" value="1"/>
