### ISSUE TITLE
[7.0.3] WPP does not generate the complete SQL output file.

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/WowPacketParser#450]
Problem detected:
WPP does not generate the complete SQL output file.

TrinityCore - WowPacketParser
Detected build: V7_0_3_22522
Detected locale: esES
Targeted database: BattleForAzeroth
Parsing date: 06/28/2019 18:46:56

Output errors:

[1/1 22522_2016-08-29_11-54-03.pkt] System.ArgumentOutOfRangeException
[1/1 22522_2016-08-29_11-54-03.pkt] El índice estaba fuera del intervalo. Debe ser un valor no negativo e inferior al tamaño de la colección.
Nombre del parámetro: index
[1/1 22522_2016-08-29_11-54-03.pkt]    en System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   en WowPacketParser.Store.Objects.UpdateFields.LegacyImplementation.ConversationData.get_Actors() en D:\WowPacketParser\WowPacketParser\Store\Objects\UpdateFields\LegacyImplementation\ConversationData.cs:línea 68
   en WowPacketParser.Store.Objects.ConversationTemplate.LoadValuesFromUpdateFields() en D:\WowPacketParser\WowPacketParser\Store\Objects\ConversationTemplate.cs:línea 41
   en WowPacketParser.SQL.Builder.DumpSQL(String prefix, String fileName, String header) en D:\WowPacketParser\WowPacketParser\SQL\Builder.cs:línea 88
   en WowPacketParser.Loading.SniffFile.WriteSQLs() en D:\WowPacketParser\WowPacketParser\Loading\SniffFile.cs:línea 522
   en WowPacketParser.Loading.SniffFile.ProcessFileImpl() en D:\WowPacketParser\WowPacketParser\Loading\SniffFile.cs:línea 273
   en WowPacketParser.Loading.SniffFile.ProcessFile() en D:\WowPacketParser\WowPacketParser\Loading\SniffFile.cs:línea 88

QuestFlags2 has undefined flags: Unk10000, Unk400000

**Comment by osleyder85** [comment]
# TrinityCore - WowPacketParser
# File name: 22522_2016-08-29_11-54-03.pkt
# Detected build: V7_0_3_22522
# Detected locale: esES
# Targeted database: BattleForAzeroth
# Parsing date: 06/28/2019 18:46:56

**Comment by ReyDonovan** [comment]
Detected build: V7_0_3_22522
Detected locale: esES
Targeted database: BattleForAzeroth -> Legion

**Comment by mdX7** [comment]
@ReyDonovan is right. But that conversation error also exists in bfa sniffs, will fix that later today

**Comment by osleyder85** [comment]
I ask:
If my DB is Battle for Azeroth and the sniffer I have is Legion, I have to choose:


 <add key="TargetedDatabase" value="4"/>   o
 <add key="TargetedDatabase" value="5"/>
