### ISSUE TITLE
Failed writing AreaTriggerTemplateVerticesData

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/WowPacketParser#455]
Detected build: 7.0.3 22522, 7.1.5 23360
Targeted database: BattleForAzeroth

Description:

2/62 - Error: Failed writing AreaTriggerTemplateVerticesData
WowPacketParser.exe Error: 0 : System.InvalidCastException: No se puede convertir un objeto DBNull en otros tipos.
   en System.DBNull.System.IConvertible.ToSingle(IFormatProvider provider)
   en System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   en WowPacketParser.SQL.SQLDatabase.Get[T](RowList`1 rowList, String database) en D:\WowPacketParser\WowPacketParser\SQL\SQLDatabase.cs:línea 246
   en WowPacketParser.SQL.Builders.AreaTriggers.AreaTriggerTemplateVerticesData() en D:\WowPacketParser\WowPacketParser\SQL\Builders\AreaTriggers.cs:línea 38

**Comment by mdX7** [comment]
cannot reproduce, tried 703, 715, 801, 815 dungeon sniffs with db disabled & enabled. Also errors in SQLDatabase.cs should not happen at all. Are you using code up to last commit - cdb3dee7f80d12e557233ded4d305ae2cf31e1d1?

**Comment by osleyder85** [comment]
No

**Comment by osleyder85** [comment]
<add key="Filters" value=""/>
        <add key="IgnoreFilters" value=""/>
        <add key="IgnoreByEntryFilters" value=""/>
        <add key="AreaFilters" value=""/>
        <add key="MapFilters" value=""/>
        <add key="FilterPacketsNum" value="0"/>
        <add key="ClientBuild" value=""/>
        <add key="TargetedDatabase" value="5"/>
        <add key="DumpFormat" value="1"/>
        <add key="IgnoreZeroValues" value="false"/>
        <add key="ForceInsertQueries" value="false"/>
        <add key="RecalcDiscount" value="false"/>      
        <add key="SQLFileName" value=""/>       
        <add key="SQLOrderByKey" value="true"/>      
        <add key="SkipOnlyVerifiedBuildUpdateRows" value="false"/>      
        <add key="ShowEndPrompt" value="true"/>      
        <add key="LogErrors" value="true"/>    
        <add key="LogPacketErrors" value="true"/>
        <add key="OutputFlag" value="15"/>  
        <add key="DebugReads" value="false"/>  
        <add key="ParsingLog" value="true"/> 
        <add key="Threads" value="1"/>
         <add key="UseDBC" value="false"/>   
        <add key="DBCPath" value="dbc"/>     
        <add key="DBCLocale" value="enUS"/> 
        <add key="ParseSpellInfos" value="false"/>


        <add key="SSHEnabled"         value="false" />
        <add key="SSHHost"            value="" />
        <add key="SSHUsername"        value="" />
        <add key="SSHPassword"        value="" />
        <add key="SSHPort"            value="22" />
        <add key="SSHLocalPort"       value="3307" />


        <add key="DBEnabled"          value="true" />
        <add key="Server"             value="localhost" />
        <add key="Port"               value="3306" />
        <add key="Username"           value="root" />
        <add key="Password"           value="trinity" />
        <add key="WPPDatabase"        value="wpp" />
        <add key="TDBDatabase"        value="world" />
        <add key="HotfixesDatabase"   value="hotfixes" /><add key="CharacterSet"       value="utf8" />
