### ISSUE TITLE
Error: The SQL output of several tables could not be generated.

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/WowPacketParser#456]
Detected build:  7.0.3 22522, 7.1.5 23360, 7.2.0 23857
Targeted database: BattleForAzeroth

Description:

8/62 - Error: Couldn't generate SQL output of GameObjectTemplateAddon since the targeted database and the sniff version don't match.
10/62 - Error: Couldn't generate SQL output of HotfixData since the targeted database and the sniff version don't match.
11/62 - Error: Couldn't generate SQL output of HotfixBlob since the targeted database and the sniff version don't match.
12/62 - Error: Couldn't generate SQL output of BroadcastText since the targeted database and the sniff version don't match.
13/62 - Error: Couldn't generate SQL output of BroadcastTextLocales since the targeted database and the sniff version don't match.
35/62 - Error: Couldn't generate SQL output of CreatureTemplateScalingData since the targeted database and the sniff version don't match.
45/62 - Error: Couldn't generate SQL output of CreatureTemplateNonWDB since the targeted database and the sniff version don't match.
50/62 - Error: Couldn't generate SQL output of QuestTemplate since the targeted database and the sniff version don't match.
51/62 - Error: Couldn't generate SQL output of QuestObjective since the targeted database and the sniff version don't match.
52/62 - Error: Couldn't generate SQL output of QuestVisualEffect since the targeted database and the sniff version don't match.
53/62 - Error: Couldn't generate SQL output of CreatureTemplate since the targeted database and the sniff version don't match.
54/62 - Error: Couldn't generate SQL output of CreatureTemplateModel since the targeted database and the sniff version don't match.
55/62 - Error: Couldn't generate SQL output of CreatureTemplateQuestItem since the targeted database and the sniff version don't match.
56/62 - Error: Couldn't generate SQL output of GameObjectTemplate since the targeted database and the sniff version don't match.
57/62 - Error: Couldn't generate SQL output of GameObjectTemplateQuestItem since the targeted database and the sniff version don't match.
58/62 - Error: Couldn't generate SQL output of ItemTemplate since the targeted database and the sniff version don't match.
59/62 - Error: Couldn't generate SQL output of PageText since the targeted database and the sniff version don't match.
60/62 - Error: Couldn't generate SQL output of NpcText since the targeted database and the sniff version don't match.
61/62 - Error: Couldn't generate SQL output of ScenarioPOI since the targeted database and the sniff version don't match.
62/62 - Error: Couldn't generate SQL output of ScenarioPOIPoint since the targeted database and the sniff version don't match.

**Comment by funjoker** [comment]
Sniff is legion targeteddb is BfA. It tells you.. no issue
