### ISSUE TITLE
Unknown column 'AnimId' in SpellAreaTriggersData

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/WowPacketParser#460]
Detected build: 7.0.3 22522
Targeted database: Legion

3/62 - Write SpellAreaTriggersData
Unknown column 'AnimId' in 'field list' at query "SELECT `SpellMiscId`, `AreaTriggerId`, `MoveCurveId`, `ScaleCurveId`, `MorphCurveId`, `FacingCurveId`, `AnimId`, `AnimKitId`, `DecalPropertiesId`, `TimeToTarget`, `TimeToTargetScale`, `VerifiedBuild` FROM world.`spell_areatrigger` WHERE (`AreaTriggerId`=9850) OR (`AreaTriggerId`=11231) OR (`AreaTriggerId`=10375) OR (`AreaTriggerId`=10366) OR (`AreaTriggerId`=10362) OR (`AreaTriggerId`=10693) OR (`AreaTriggerId`=10356) OR (`AreaTriggerId`=10350) OR (`AreaTriggerId`=9905) OR (`AreaTriggerId`=9637) OR (`AreaTriggerId`=10355) OR (`AreaTriggerId`=9877) OR (`AreaTriggerId`=6669) OR (`AreaTriggerId`=8352)"

**Comment by mdX7** [comment]
your database is not up2date
ref: https://github.com/TrinityCore/WowPacketParser/blob/master/WowPacketParser/Store/Objects/SpellAreaTrigger.cs#L31
ref: https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Entities/AreaTrigger/AreaTriggerTemplate.h#L207
