### ISSUE TITLE
Error: Failed writing GameObjectTemplateAddon

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/WowPacketParser#461]
Detected build: 7.0.3 22522
Targeted database: Legion

8/62 - Error: Failed writing GameObjectTemplateAddon
WowPacketParser.exe Error: 0 : System.IndexOutOfRangeException: Índice fuera de los límites de la matriz.
   en WowPacketParser.Store.Objects.UpdateFields.LegacyImplementation.UpdateFieldExtensions.GetEnum[T,TK](Dictionary`2 dict, T updateField) en D:\WowPacketParser\WowPacketParser\Store\Objects\UpdateFields\LegacyImplementation\UpdateFieldExtensions.cs:línea 163
   en WowPacketParser.SQL.Builders.GameObjectMisc.GameObjectTemplateAddon(Dictionary`2 gameobjects) en D:\WowPacketParser\WowPacketParser\SQL\Builders\GameObjectMisc.cs:línea 49

**Comment by mdX7** [comment]
cannot reproduce (tried sniff of the same build), maybe invalid sniff. Could you hand me over the sniff via. IRC or Discord so I may look into it?

**Comment by osleyder85** [comment]
Yes, via Discord

**Comment by Shauren** [comment]
17d8bff5264024b9f4404f7d1c3f775109b340d4
