### ISSUE TITLE
Unknown column 'SpawnTrackingID' in QuestPOI

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/WowPacketParser#462]
Detected build: 7.0.3 22522
Targeted database: Legion

27/62 - Write QuestPOI
Unknown column 'SpawnTrackingID' in 'field list' at query "SELECT `QuestID`, `BlobIndex`, `Idx1`, `ObjectiveIndex`, `QuestObjectiveID`, `QuestObjectID`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `SpawnTrackingID`, `AlwaysAllowMergingBlobs`, `VerifiedBuild` FROM world.`quest_poi` WHERE (`QuestID`=38725 AND `BlobIndex`=0 AND `Idx1`=1) OR (`QuestID`=38725 AND `BlobIndex`=0 AND `Idx1`=0) OR (`QuestID`=38819 AND `BlobIndex`=0 AND `Idx1`=4) OR (`QuestID`=38819 AND `BlobIndex`=2 AND `Idx1`=3) OR (`QuestID`=38819 AND `BlobIndex`=1 AND `Idx1`=2) OR (`QuestID`=38819 AND `BlobIndex`=0 AND `Idx1`=1) OR (`QuestID`=38819 AND `BlobIndex`=0 AND `Idx1`=0) OR (`QuestID`=38727 AND `BlobIndex`=0 AND `Idx1`=4) OR (`QuestID`=38727 AND `BlobIndex`=0 AND `Idx1`=3) OR (`QuestID`=38727 AND `BlobIndex`=0 AND `Idx1`=2) OR (`QuestID`=38727 AND `BlobIndex`=0 AND `Idx1`=1) OR (`QuestID`=38727 AND `BlobIndex`=0 AND `Idx1`=0) OR (`QuestID`=39495 AND `BlobIndex`=0 AND `Idx1`=2) OR (`QuestID`=39495 AND `BlobIndex`=0 AND `Idx1`=1) OR (`QuestID`=39495 AND `BlobIndex`=0 AND `Idx1`=0) OR (`QuestID`=39262 AND `BlobIndex`=0 AND `Idx1`=3) OR (`QuestID`=39262 AND `BlobIndex`=0 AND `Idx1`=2) OR (`QuestID`=39262 AND `BlobIndex`=0 AND `Idx1`=1) OR (`QuestID`=39262 AND `BlobIndex`=0 AND `Idx1`=0) OR (`QuestID`=38813 AND `BlobIndex`=0 AND `Idx1`=4) OR (`QuestID`=38813 AND `BlobIndex`=0 AND `Idx1`=3) OR (`QuestID`=38813 AND `BlobIndex`=0 AND `Idx1`=2) OR (`QuestID`=38813 AND `BlobIndex`=0 AND `Idx1`=1) OR (`QuestID`=38813 AND `BlobIndex`=0 AND `Idx1`=0) OR (`QuestID`=38766 AND `BlobIndex`=0 AND `Idx1`=2) OR (`QuestID`=38766 AND `BlobIndex`=0 AND `Idx1`=1) OR (`QuestID`=38766 AND `BlobIndex`=0 AND `Idx1`=0) OR (`QuestID`=38765 AND `BlobIndex`=0 AND `Idx1`=3) OR (`QuestID`=38765 AND `BlobIndex`=0 AND `Idx1`=2) OR (`QuestID`=38765 AND `BlobIndex`=0 AND `Idx1`=1) OR (`QuestID`=38765 AND `BlobIndex`=0 AND `Idx1`=0) OR (`QuestID`=39050 AND `BlobIndex`=0 AND `Idx1`=2) OR (`QuestID`=39050 AND `BlobIndex`=0 AND `Idx1`=1) OR (`QuestID`=39050 AND `BlobIndex`=0 AND `Idx1`=0) OR (`QuestID`=40379 AND `BlobIndex`=0 AND `Idx1`=3) OR (`QuestID`=40379 AND `BlobIndex`=0 AND `Idx1`=2) OR (`QuestID`=40379 AND `BlobIndex`=0 AND `Idx1`=1) OR (`QuestID`=40379 AND `BlobIndex`=0 AND `Idx1`=0) OR (`QuestID`=39049 AND `BlobIndex`=0 AND `Idx1`=2) OR (`QuestID`=39049 AND `BlobIndex`=0 AND `Idx1`=1) OR (`QuestID`=39049 AND `BlobIndex`=0 AND `Idx1`=0) OR (`QuestID`=38759 AND `BlobIndex`=0 AND `Idx1`=6) OR (`QuestID`=38759 AND `BlobIndex`=0 AND `Idx1`=5) OR (`QuestID`=38759 AND `BlobIndex`=0 AND `Idx1`=4) OR (`QuestID`=38759 AND `BlobIndex`=0 AND `Idx1`=3) OR (`QuestID`=38759 AND `BlobIndex`=0 AND `Idx1`=2) OR (`QuestID`=38759 AND `BlobIndex`=0 AND `Idx1`=1) OR (`QuestID`=38759 AND `BlobIndex`=0 AND `Idx1`=0) OR (`QuestID`=40378 AND `BlobIndex`=0 AND `Idx1`=4) OR (`QuestID`=40378 AND `BlobIndex`=0 AND `Idx1`=3) OR (`QuestID`=40378 AND `BlobIndex`=0 AND `Idx1`=2) OR (`QuestID`=40378 AND `BlobIndex`=0 AND `Idx1`=1) OR (`QuestID`=40378 AND `BlobIndex`=0 AND `Idx1`=0) OR (`QuestID`=39279 AND `BlobIndex`=0 AND `Idx1`=5) OR (`QuestID`=39279 AND `BlobIndex`=0 AND `Idx1`=4) OR (`QuestID`=39279 AND `BlobIndex`=0 AND `Idx1`=3) OR (`QuestID`=39279 AND `BlobIndex`=0 AND `Idx1`=2) OR (`QuestID`=39279 AND `BlobIndex`=1 AND `Idx1`=1) OR (`QuestID`=39279 AND `BlobIndex`=0 AND `Idx1`=0) OR (`QuestID`=40077 AND `BlobIndex`=0 AND `Idx1`=3) OR (`QuestID`=40077 AND `BlobIndex`=0 AND `Idx1`=2) OR (`QuestID`=40077 AND `BlobIndex`=0 AND `Idx1`=1) OR (`QuestID`=40077 AND `BlobIndex`=0 AND `Idx1`=0)"

**Comment by mdX7** [comment]
your database is not up2date. SpawnTrackingID exists in db since wod (and is even present in current bfa)
ref: https://github.com/TrinityCore/WowPacketParser/blob/master/WowPacketParser/Store/Objects/QuestPOI.cs#L53
