### ISSUE TITLE
Data in unnecessary `quest_details`.

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/WowPacketParser#470]
Detected build: 7.0.3.22522
Targeted database: Legion

What is the objective of adding this data to the Database?

```
INSERT INTO `quest_details` (`ID`, `Emote1`, `Emote2`, `Emote3`, `Emote4`, `EmoteDelay1`, `EmoteDelay2`, `EmoteDelay3`, `EmoteDelay4`, `VerifiedBuild`) VALUES
(38765, 0, 0, 0, 0, 0, 0, 0, 0, 22522), -- Enter the Illidari: Shivarra
(39049, 0, 0, 0, 0, 0, 0, 0, 0, 22522), -- Eye On the Prize
(38759, 0, 0, 0, 0, 0, 0, 0, 0, 22522), -- Set Them Free
(40378, 0, 0, 0, 0, 0, 0, 0, 0, 22522), -- Enter the Illidari: Ashtongue
(40077, 0, 0, 0, 0, 0, 0, 0, 0, 22522); -- The Invasion Begins
```

**Comment by mdX7** [comment]
the packet where we build the data for `quest_details` has much more data than only emote stuff (but we got that also covered elsewhere). I guess this was done this was in the first place if we require more data from that packet.

**Comment by funjoker** [comment]
In my opinion it's not unnecessary.
It proofs that a quest has no emotes.
If we stop adding this data it would mean, that there could be data or there couldn't not be data.

**Comment by mdX7** [comment]
agreed
