### ISSUE TITLE
WPP does not generate the sql output file.

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/WowPacketParser#489]
Detected build: V8.0.1_27377
Targeted database: Battle for Azeroth

This is the converter you use to take the sniffer from awps to pkt:
[Converter](https://mega.nz/#!IVIDDCIA!dfN3TH1S_6ucnl6kc_WjCSY-cs_Fh7ah8EVbLppCf_w)

This is my configuration file:
[WowPacketParser.exe.config](https://mega.nz/#!pAgThYTb!fPQGmGTKD-au1V9VCYBt2TcSoe-tQHTNDNUQQqeR7N8)

Output file in txt, the only file generated:
[Log.txt](https://mega.nz/#!NYoF3YqL!5PFrKl_HZni1ULze0OUV8IzSM2vDnGfu8LqW0IE8fZY)

**Comment by funjoker** [comment]
Which settings you had?

**Comment by osleyder85** [comment]
Here is my configuration with the output log.

[WowPacketParser.exe.config](https://mega.nz/#!pAgThYTb!fPQGmGTKD-au1V9VCYBt2TcSoe-tQHTNDNUQQqeR7N8)
[Log.txt](https://mega.nz/#!NYoF3YqL!5PFrKl_HZni1ULze0OUV8IzSM2vDnGfu8LqW0IE8fZY)

**Comment by osleyder85** [comment]
A question:
Can I use a converter with version 8.1.0 and convert files with build 8.0.1?

**Comment by osleyder85** [comment]
Already all solved, it was a bad configuration in the converter.
