### ISSUE TITLE
Error: System.IO.EndOfStreamException - CMSG_WHO

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/WowPacketParser#501]
Detected build: V8_0_1_27178
Targeted database: BattleForAzeroth

ClientToServer: CMSG_WHO (0x3681) Length: 42 ConnIdx: 0 Time: 08/02/2018 14:32:39.779 Number: 3227
WhoWordCount: 0
MinLevel: 0
MaxLevel: 123
RaceFilter: -1
ClassFilter: -1
ShowEnemies: True
ShowArenaPlayers: False
ExactName: False
HasServerInfo: False
Name: SzäksziRagnaros
VirtualRealmName: 
Guild: 
GuildVirtualRealmName: 
System.IO.EndOfStreamException
No se puede leer más allá del final de la secuencia.
   en System.IO.__Error.EndOfFile()
   en System.IO.BinaryReader.ReadByte()
   en WowPacketParser.Misc.Packet.ReadBit() en D:\WowPacketParser\WowPacketParser\Misc\PacketReads.cs:línea 588
   en WowPacketParser.Misc.Packet.ReadBits(Int32 bits) en D:\WowPacketParser\WowPacketParser\Misc\PacketReads.cs:línea 617
   en WowPacketParserModule.V6_0_2_19033.Parsers.MiscellaneousHandler.HandleWhoRequest(Packet packet) en D:\WowPacketParser\WowPacketParserModule.V6_0_2_19033\Parsers\MiscellaneousHandler.cs:línea 306
   en WowPacketParser.Parsing.Handler.Parse(Packet packet, Boolean isMultiple) en D:\WowPacketParser\WowPacketParser\Parsing\Handler.cs:línea 149

**Comment by funjoker** [comment]
retry pls
