### ISSUE TITLE
Incorrect data in the output SQL: `conversation_actor_template` table

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/WowPacketParser#522]
- TrinityCore - WowPacketParser
- Detected build: V8_0_1_27404
- Detected locale: enUS
- Targeted database: BattleForAzeroth
- Parsing date: 11/25/2019 15:24:18

The `Id` of the `conversation_actor_template` table is the same as the `CreatureId` of the creature, I think that is incorrect.

Incorrect data:
```sql
DELETE FROM `conversation_actor_template` WHERE `Id` IN (124651, 124787, 125138, 125496, 126309, 126794, 130367, 133243, 134163, 134201, 134282, 137109, 139491, 140039, 140126, 140129, 144380);
INSERT INTO `conversation_actor_template` (`Id`, `CreatureId`, `CreatureModelId`, `VerifiedBuild`) VALUES
(124651, 124651, 86014, 27404),
(124787, 124787, 88348, 27404),
(125138, 125138, 86013, 27404),
(125496, 125496, 31177, 27404),
(126309, 126309, 86008, 27404),
(126794, 126794, 82723, 27404),
(130367, 130367, 86015, 27404),
(133243, 133243, 86011, 27404),
(134163, 134163, 83367, 27404),
(134201, 134201, 80016, 27404),
(134282, 134282, 71764, 27404),
(137109, 137109, 86012, 27404),
(139491, 139491, 86323, 27404),
(140039, 140039, 87522, 27404),
(140126, 140126, 73176, 27404),
(140129, 140129, 65552, 27404),
(144380, 144380, 88541, 27404);
```
I don't know, this created a certain doubt. If it's okay, they tell me.
Regards.

**Comment by mdX7** [comment]
This is intended behaviour. During Legion we had a separate Id field in UpdateFields of conversations, but in BfA/8.0.1 this was dropped by Blizzard.

Ref: https://github.com/TrinityCore/WowPacketParser/commit/89a3728e06211a0174a0f5691a78209e2f7c5dde
