### ISSUE TITLE
Wpp not parse any data of creature or creature_template

### ISSUE THREAD

**Issue by Thordekk** [TrinityCore/WowPacketParser#548]
Wpp not parse any data of creature or creature_template

**Comment by jackpoz** [comment]
any additional information that might help fixing it ? which wow version was your sniff from ? what does the console say ? any exception ? anything useful at all ?

**Comment by funjoker** [comment]
please information

**Comment by Thordekk** [comment]
Version 8.0.1  i think if u put in config target database =5 bfa that happend

**Comment by Thordekk** [comment]
I put target db wtlk and now parse creature template

**Comment by funjoker** [comment]
Any console output ?
