### ISSUE TITLE
Billing flags explanation

### ISSUE THREAD

**Issue by Simplaf234** [TrinityCore/WowPacketParser#555]
In https://github.com/TrinityCore/WowPacketParser/blob/master/WowPacketParser/Enums/BillingFlag.cs, what do these flags mean:

```
        Restricted       = 0x40,
        EnableCais       = 0x80
```
?

Is TimeMixture (0x20) used together with all billing flags available or just active one?

Were all of these billing flags available from patch 1.1 or some of them were added later?

**Comment by Shauren** [comment]
I don't know.

**Comment by Simplaf234** [comment]
> I don't know.

Why close it immediately? Someone else might know.

**Comment by Shauren** [comment]
Because this is a question, not an issue

**Comment by Aokromes** [comment]
also, not supported opcode.
