### ISSUE TITLE
System.ArgumentOutOfRangeException for V3_3_5a_12340

### ISSUE THREAD

**Issue by Faq** [TrinityCore/WowPacketParser#559]
Looks like problem to parse leveling achievements.

Reproduce steps:
`on lvl1 character use command .level 79`

[log here ](https://gist.github.com/Faq/58ea15836127eb023451330a28a2ee1c)

**Comment by funjoker** [comment]
can you test again please

**Comment by Faq** [comment]
it showed different problems, shared info on discord.

**Comment by Faq** [comment]
It is ok now on https://github.com/TrinityCore/WowPacketParser/commit/477ecaa704ab3348cdc7e0d15db043cda399207f
