### ISSUE TITLE
missing battlepay and lfg list structure

### ISSUE THREAD

**Issue by arcaniafr** [TrinityCore/WowPacketParser#564]
Someone have the structure for the opcode
SMSG_BATTLE_PAY_GET_PRODUCT_LIST_RESPONSE
& SMSG_LFG_LIST_JOIN_RESULT

Thanks for reply

**Comment by funjoker** [comment]
Battlepay won’t be fixed.

**Comment by arcaniafr** [comment]
why? with custom script it's possible, no? I want to try but I would like to have the structure of SMSG_BATTLE_PAY_GET_PRODUCT_LIST_RESPONSE can you help me please you have discord?

**Comment by Aokromes** [comment]
no, we don't go to support battlepay.

**Comment by arcaniafr** [comment]
and lfg_list?

**Comment by funjoker** [comment]
i can take a look

**Comment by funjoker** [comment]
may take some time, have no stuff set up atm

**Comment by funjoker** [comment]
SMSG_LFG_LIST_JOIN_RESULT already fixed:
https://github.com/TrinityCore/WowPacketParser/blob/master/WowPacketParserModule.V7_0_3_22248/Parsers/LfgHandler.cs#L138

valid for 8.x
