### ISSUE TITLE
Parser can't get SpellMiscId from pkt

### ISSUE THREAD

**Issue by ImmortalusDev** [TrinityCore/WowPacketParser#566]
DELETE FROM `spell_areatrigger` WHERE (`AreaTriggerId`=0);
INSERT INTO `spell_areatrigger` (`SpellMiscId`, `AreaTriggerId`, `MoveCurveId`, `ScaleCurveId`, `MorphCurveId`, `FacingCurveId`, `AnimId`, `AnimKitId`, `DecalPropertiesId`, `TimeToTarget`, `TimeToTargetScale`, `VerifiedBuild`) VALUES
(UNKNOWN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 500, 31478); -- SpellId : 265163

**Comment by funjoker** [comment]
Did you use DBCs ?

**Comment by ImmortalusDev** [comment]
<add key="UseDBC" value="false"/>

**Comment by funjoker** [comment]
That's the issue. Use DBCs

**Comment by ImmortalusDev** [comment]
Ah, i'm dumb :D Thanks!
