### ISSUE TITLE
Add data from SMSG_WORLD_QUEST_UPDATE_RESPONSE in output_file.sql

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/WowPacketParser#569]
Change proposal:

Add the data from SMSG_WORLD_QUEST_UPDATE_RESPONSE to the output_file.sql. Required to update the world_quest.

Create the world_quest table in the World database:
```
DROP TABLE IF EXISTS `world_quest`;
CREATE TABLE `world_quest` (
  `QuestID` INT (10) UNSIGNED NOT NULL,
  `Timer` INT (10) UNSIGNED NOT NULL,
  `VariableID` INT (10) NOT NULL,
  `Value` INT (10) NOT NULL,
  `VerifiedBuild` SMALLINT(5) DEFAULT 0 NULL,
  PRIMARY KEY (`QuestID`)
);
```
Example Data:
```
ServerToClient: SMSG_WORLD_QUEST_UPDATE_RESPONSE (0x2853) Length: 3204 ConnIdx: 0 Time: 08/30/2020 21:26:16.025 Number: 21286
Count: 160
[0] LastUpdate: 08/30/2020 13:15:29
[0] QuestID: 39424 (Everything!)
[0] Timer: 86400
[0] VariableID: 11131
[0] Value: 1
```
Insert in the Database:
```
DELETE FROM `world_quest` WHERE `QuestID` IN (39424);
INSERT INTO `world_quest`(`QuestID`, `Timer`, `VariableID`, `Value`, `VerifiedBuild`) VALUES
(39424, 86400, 11131, 1, 31478), -- Everything!
```

**Comment by mdX7** [comment]
that table does not exist in trinitycore yet. The worldquest system itself is not yet implemented as stated here https://github.com/TrinityCore/TrinityCore/blob/f922c6e7a46a7c712daaaef9b1a72ca865fbe94b/src/server/game/Handlers/QuestHandler.cpp#L672

We'll add a proper sql generator to wpp as soon as it's implemented in TrinityCore.
