### ISSUE TITLE
Parse isnt parse waypoints

### ISSUE THREAD

**Issue by FCondeNR** [TrinityCore/WowPacketParser#574]
Actually the WPP isnt parsing the diferents waypoints of creatures, will amazing introduct it, becouse the sniffer is giving that info. TY and Merry XMAS!!!

**Comment by Faq** [comment]
Any example file with waypoints to parse?

**Comment by shamage** [comment]
> Actually the WPP isnt parsing the diferents waypoints of creatures, will amazing introduct it, becouse the sniffer is giving that info. TY and Merry XMAS!!!

I'm not sure what you meant exactly, but WPP is not for parsing the diferents waypoints of creatures, I have a tip for you where we can analyze and edit points for a creature you have this for that : [WaypointCreator ](https://github.com/TrinityCore/WaypointCreator) .
@mdX7  - this could also be closed
