### ISSUE TITLE
Multiple different values for creature_model_info should be ignored

### ISSUE THREAD

**Issue by mdX7** [TrinityCore/WowPacketParser#598]
When we have multiple values for one entry in creature_model_info (CombatReach/BoundingRadius stuff) we should ignore them in SQL output since its likely caused by some auras.

**Comment by offl** [comment]
I still didn't rechecked that thing but I'm pretty sure it was not caused by auras
https://github.com/TrinityCore/TrinityCore/discussions/25964#discussioncomment-494815

**Comment by mdX7** [comment]
2d3244461ec5b34a93b2b58dadd0b491a6344f19
