### ISSUE TITLE
Parsing Issue 335: `spawndist` + `PhaseGroup`

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/WowPacketParser#643]
Fore the 3.3.5 database output there are some error:

1) `spawndist` should be renamed to `wander_distance`
2) `PhaseGroup` is not a part of 3.3.5 db and should be removed 

@mdX7 :)

**Comment by mdX7** [comment]
wander distance fix done in 8c629e0264955b142e6d34ec4af321fcf8766ff1

**Comment by Rushor** [comment]
thank you!
