### ISSUE TITLE
max_allowed_packet error

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/WowPacketParser#649]
When parsing large sniffs with quest_pois the query exceed max_allowed_packet default size.

**Comment by mdX7** [comment]
we cannot force `max_allowed_packet` with current sql connector. Fabian recently suggested https://github.com/mysql-net/MySqlConnector/ to me, will look into that

**Comment by Shauren** [comment]
What exactly is the problem here? WPP not being able to query existing db or the output sql file producing a query that exceeds default max_allowed_packet? If its the second one then this is not an issue at all.

**Comment by mdX7** [comment]
First thing due to insanely long WHERE in the SELECT statement when parsing quest_poi brute
