### ISSUE TITLE
SQL output is missing gameobjects

### ISSUE THREAD

**Issue by Tobschinski** [TrinityCore/WowPacketParser#674]
I noticed that the sql output (TBC) is missing valid gameobjects whenever there are transports sniffed. (In this case: the zeppelin in Tirisfal when I tried to get herbs in Scarlet Monastery)

The overall amount does not change when they are not there, so they probably overwrite something somewhere.

**Comment by neifion-00000000** [comment]
nice job figuring this out I was confused what the commonality was

**Comment by Shauren** [comment]
Don't try to guess the reason in code, better to give more details

What is missing? `gameobject_template` or `gameobject`?
Do you have db connection enabled to load already existing gameobject templates?

**Comment by killerwife** [comment]
Forwarded the info and data to shauren on discord. Gameobject table.
