### ISSUE TITLE
Output file.sql doesn't show creature or gameobject spawns

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/WowPacketParser#695]
TrinityCore - WowPacketParser
Detected build: V9_2_7_45161
Detected locale: enUS
Targeted database: Shadowlands

Output file.sql doesn't show creature or gameobject spawns

**Comment by mdX7** [comment]
Update to https://github.com/TrinityCore/WowPacketParser/commit/54a1e746449feb856f51bdf69569adf0bd5caba1
