### ISSUE TITLE
How to get .pkt or .bin files that mentioned in readme?

### ISSUE THREAD

**Issue by ErcinDedeoglu** [TrinityCore/WowPacketParser#724]
Hello folks,
How can I get .pkt or .bin files which are mentioned in README file.
-- Drag one or more files (.pkt or .bin) to WowPacketParser.exe.

**Comment by mdX7** [comment]
With a sniffer, which captures packets sent and received of the client.
https://github.com/trinitycore/ymir
Is the most used one nowadays
