### ISSUE TITLE
PhaseId has incorrect type

### ISSUE THREAD

**Issue by humanpride** [TrinityCore/WowPacketParser#774]
After parsing sniff file from rtl game 49741 I have the issue with data in PhaseId column. In DB creature/gameobj column has integer type, in parsed file it's a string.
Example:
```
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnDifficulties`, `PhaseId`, ...
(@CGUID+0, 174971, 2261, 10424, 10639, '0', '15284 - 14355 - 15286 - 13753 - 14349', ...
```
Looks like a bug.
If I missed some config, let me know, please.

WPP ver. a0f17ccb

**Comment by Naddley** [comment]
Thats intended. Wpp shows every active Phase on Player.

**Comment by mdX7** [comment]
working as intended, you have to figure out the related phase of the npc (its either one of the listed ones or 0) by trying to despawn/spawn him (e.g. by doing quests, abandoning quests) etc.
Rule of thumb is that an attackable npc is phase 0
