### ISSUE TITLE
creature_template_difficulty generation

### ISSUE THREAD

**Issue by ImmortalusDev** [TrinityCore/WowPacketParser#813]
It generates nothing, last three builds for sure.

**Comment by Thordekk** [comment]
It work perfect for me so is some on youre side

**Comment by mdX7** [comment]
Keep in mind the table is also using wdb data, that means you have to make sure u delete cache before launching wow

**Comment by Ovahlord** [comment]
difficulty entries are only being generated once for the initial insertion. For all further difficulties, you have to create own entries because health and mana mods for example need to be manually calculated.
