### ISSUE TITLE
missing wow classic era builds

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/WowPacketParser#888]
malcrom said recent builds cannot be parsed, i found all those builds missing:

1.14.4.51001
1.14.4.51056
1.14.4.51146
1.14.4.51311
1.14.4.51395

1.14.4.51829

1.15.0.52146
1.15.0.52186
1.15.0.52212

1.15.0.52409

1.15.1.53181

1.15.1.53495
1.15.1.53623

1.15.2.54029
1.15.2.54067
1.15.2.54092

1.15.2.54332
1.15.2.54649
1.15.2.54902
1.15.2.55002
1.15.2.55140

1.15.3.55515
1.15.3.55563
1.15.3.55646
1.15.3.55917
1.15.3.56488
1.15.3.56626

1.15.4.56738
1.15.4.56760
1.15.4.56817
1.15.4.56857

**Comment by Ovahlord** [comment]
They won't be parsable by adding the builds either because nobody did the opcodes or update fields

**Comment by Aokromes** [comment]
well, it's a list of missing builds just in case someone want to work with them.
