### ISSUE TITLE
DotNetZip must be replaced

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/WowPacketParser#896]
it's not longer maintained, and it spams weekly

**Comment by Fabi** [comment]
That was a replace of one not maintained lib with another. Please reopen

**Comment by MaxtorCoder** [comment]
What even is that library used for?

**Comment by Fabi** [comment]
> What even is that library used for?

zlib compression stuff in packets here and there

**Comment by Aokromes** [comment]
> That was a replace of one not maintained lib with another (basically the same lib). Please reopen. Not solved at all

well, as long it doesnt spams me weekly it's ok for me xd
